const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const SAVE_KEY="taruto-quest-save-v2",SCORE_KEY="taruto-quest-best-score",MAX_LEVEL=50;
const stages=[
  {name:"はじまりの草原",chapter:"CHAPTER 1",gate:5,quota:3,boss:"mayu",enemies:[
    ["ぷるぷるゼリー","🟢"],["いたずらカラス","🐦‍⬛"],["みはりネコ","🐈‍⬛"],["おおきなアヒル","🦆"]]},
  {name:"木漏れ日の森",chapter:"CHAPTER 2",gate:10,quota:4,enemies:[
    ["まほうキノコ","🍄"],["森のオオカミ","🐺"],["どんぐり兵","🌰"],["ねむねむフクロウ","🦉"]]},
  {name:"夕暮れの洞窟",chapter:"CHAPTER 3",gate:20,quota:5,enemies:[
    ["ねむねむコウモリ","🦇"],["ごろごろ岩","🪨"],["どくどくヘビ","🐍"],["洞窟グモ","🕷️"]]},
  {name:"ドラゴンの山",chapter:"CHAPTER 4",gate:30,quota:5,enemies:[
    ["あばれイノシシ","🐗"],["こおりの精","❄️"],["空飛ぶトカゲ","🦎"],["ファイアドラゴン","🐉"]]},
  {name:"おやつ魔王城",chapter:"CHAPTER 5",gate:40,quota:6,enemies:[
    ["やみの番犬","🐕‍🦺"],["ひとくい宝箱","🧰"],["よろい兵","🛡️"],["魔王の手下","👿"]]},
  {name:"こうきの間",chapter:"FINAL CHAPTER",gate:50,quota:7,boss:"kouki",enemies:[
    ["闇のドラゴン","🐲"],["最強の番犬","🐺"],["魔界の騎士","♞"],["おやつの魔人","👹"]]}
];
const miniBosses=[
  {name:'大空のワシ',icon:'🦅'},
  {name:'はらぺこコヨーテ',icon:'🐺'},
  {name:'どく牙のマムシ',icon:'🐍'},
  {name:'山のツキノワグマ',icon:'🐻'},
  {name:'魔城のオオヤマネコ',icon:'🐆'},
  {name:'猛突進イノシシ王',icon:'🐗'}
];
let state,battle,busy=false,sound=true,pendingLevelDetails=null;
const musicTracks={
  title:{src:'assets/mayu-kawaii-8bit.mp3',volume:.22,loop:true},map:{src:'assets/mayu-kawaii-8bit.mp3',volume:.18,loop:true},
  regular:{src:'assets/audio/quest-regular.ogg',volume:.24,loop:true},miniboss:{src:'assets/audio/quest-miniboss.mp3',volume:.27,loop:true},
  mayu:{src:'assets/audio/quest-mayu.mp3',volume:.25,loop:true},kouki1:{src:'assets/audio/quest-kouki-phase1.mp3',volume:.27,loop:true},
  kouki2:{src:'assets/audio/quest-kouki-phase2.ogg',volume:.29,loop:true},victory:{src:'assets/audio/quest-victory.mp3',volume:.28,loop:false}
};
const musicPlayers=Object.fromEntries(Object.entries(musicTracks).map(([key,track])=>{const audio=new Audio(track.src);audio.loop=track.loop;audio.volume=track.volume;audio.preload='auto';return[key,audio]}));
let currentMusicKey='title';
const skills={spin:{name:'くるん',mp:3,speed:12},bite:{name:'かみつき',mp:5,speed:-3},bark:{name:'吠え',mp:8,speed:0},tail:{name:'しっぽを振り回す',mp:6,speed:2},dig:{name:'穴を掘る',mp:4,speed:8},snack:{name:'おやつパワー',mp:6,speed:5},tackle:{name:'たるとタックル',mp:3,speed:999},father:{name:'とーちゃん応援',mp:8,speed:4},motherSupport:{name:'かーちゃん応援',mp:10,speed:6},rampage:{name:'たると大暴走',mp:20,speed:3},supreme:{name:'天上天下唯我独尊',mp:50,speed:10},water:{name:'お水',mp:0,speed:4},mother:{name:'かーちゃんなでなで',mp:12,speed:6}};
function fresh(){return{level:1,exp:0,hp:34,mp:12,carrots:3,waters:3,stage:0,areaWins:0,miniBossDefeated:false,totalWins:0,score:0,mapSeed:Math.floor(Math.random()*1e9),started:Date.now()}}
function expForNext(lv){return lv>=MAX_LEVEL?0:30+lv*12}
function stats(lv=state.level){return{maxHp:34+(lv-1)*6,maxMp:12+(lv-1)*2,atk:8+(lv-1)*2.35,def:3+(lv-1)*1.25,spd:6+(lv-1)*1.5}}
function save(){try{state.savedAt=Date.now();localStorage.setItem(SAVE_KEY,JSON.stringify(state));const info=$('#saveInfo');if(info)info.textContent=`保存 ${new Date(state.savedAt).toLocaleTimeString('ja-JP',{hour:'2-digit',minute:'2-digit'})}`}catch(_){}}
function load(){try{const d=JSON.parse(localStorage.getItem(SAVE_KEY));return d&&d.stage<stages.length?d:null}catch(_){return null}}
function beep(freq=440,d=.06){if(!sound)return;try{const a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=freq;o.type="square";g.gain.setValueAtTime(.03,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.connect(g).connect(a.destination);o.start();o.stop(a.currentTime+d)}catch(_){}}
function playMusic(key,restart=false){if(!musicPlayers[key])return;const previous=musicPlayers[currentMusicKey];if(currentMusicKey!==key&&previous){previous.pause();previous.currentTime=0}currentMusicKey=key;const audio=musicPlayers[key];if(restart){audio.pause();audio.currentTime=0}if(sound&&audio.paused)audio.play().catch(()=>{})}
function pauseMusic(){Object.values(musicPlayers).forEach(audio=>audio.pause())}
async function enterFullscreen(){try{if(!isSecureContext)throw Error();if(!document.fullscreenElement){const root=document.documentElement,fn=root.requestFullscreen||root.webkitRequestFullscreen;if(fn)await fn.call(root,{navigationUI:"hide"})}}catch(_){if(!isSecureContext)alert("ローカルHTTPではAndroidの全画面表示が制限されます。HTTPS公開版をホーム画面へ追加すると全画面で遊べます。")};setTimeout(()=>scrollTo(0,1),100)}
function show(id){$$('.screen').forEach(s=>s.classList.add('hidden'));$(id).classList.remove('hidden')}
function init(){const data=load();$('#continueBtn').classList.toggle('hidden',!data);$('#deleteSaveBtn').classList.toggle('hidden',!data);if(data)$('#continueBtn').textContent=`つづきから（LV ${data.level}）`;renderNodes();playMusic('title')}
function startNew(){enterFullscreen();state=fresh();save();showMap()}
function continueGame(){enterFullscreen();state=load()||fresh();normalizeState();showMap()}
function normalizeState(){const s=stats();state.hp=Math.min(state.hp||s.maxHp,s.maxHp);state.mp=Math.min(state.mp||s.maxMp,s.maxMp);state.waters=Number.isFinite(state.waters)?state.waters:3;state.areaWins=state.areaWins||0;state.miniBossDefeated=Boolean(state.miniBossDefeated);state.totalWins=state.totalWins||0}
function renderNodes(){const wrap=$('#mapNodes');wrap.innerHTML='';stages.forEach((s,i)=>{const n=document.createElement('span');n.className='map-node'+(s.boss?' boss':'');n.textContent=s.boss?'★':i+1;wrap.appendChild(n)})}
function stageReady(){const s=stages[state.stage];return state.areaWins>=s.quota&&state.level>=s.gate}
function mapMessage(custom){const s=stages[state.stage];if(custom)return custom;if(state.areaWins<s.quota)return `敵グループをあと ${s.quota-state.areaWins}回 倒して小ボスへの道をひらこう！`;if(state.level<s.gate)return `小ボスに挑むには レベル${s.gate} が必要！ あと${s.gate-state.level}レベル。`;if(!state.miniBossDefeated)return `小ボス「${miniBosses[state.stage].name}」が待ち受けている！`;return s.boss?(s.boss==='mayu'?'小ボスの先で、まゆが待ち受けている！':'小ボスの先で、こうきが待ち受けている！'):'次のステージへの道がひらいた！'}
function showMap(custom){show('#mapScreen');renderNodes();const a=stages[state.stage],s=stats();$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=a.chapter;$('#locationName').textContent=a.name;$('#mapMessage').textContent=mapMessage(custom);$$('.map-node').forEach((n,i)=>{n.classList.toggle('done',i<state.stage);n.classList.toggle('current',i===state.stage)});$('.map-taruto').style.left=`${4+state.stage*16}%`;if(stageReady())$('#advanceBtn').textContent=!state.miniBossDefeated?`${miniBosses[state.stage].name}に挑む！`:a.boss?(a.boss==='mayu'?'まゆに挑む！':'こうきに挑む！'):'次のステージへ';else $('#advanceBtn').textContent=state.areaWins<a.quota?'敵をさがす':'レベル上げをする';$('#restBtn').textContent=`ひとやすみ（全回復）　次のLVまで ${expForNext(state.level)-state.exp} EXP`;save()}
function rest(){const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;showMap('ひとやすみして元気いっぱい！');beep(660)}
function advance(){const a=stages[state.stage];if(stageReady()){if(!state.miniBossDefeated){beginMiniBoss();return}if(a.boss){beginBoss(a.boss);return}}beginMobBattle()}
function enemyScale(){return Math.max(1,state.level-1+Math.floor(Math.random()*3))}
const fixedEnemyStats=new Map(stages.flatMap(stage=>stage.enemies).map((enemy,index)=>{const rank=index+1;return[enemy[0],{rank,lv:Math.min(50,rank*2-1),hp:18+(rank-1)*12,atk:3+(rank-1)*1.5,spd:4+(rank-1)*1.2,xp:8+(rank-1)*8}]}));
function makeEnemy(template,i,count){const fixed=fixedEnemyStats.get(template[0]),maxHp=Math.round(fixed.hp);return{name:template[0],icon:template[1],rank:fixed.rank,lv:fixed.lv,maxHp,currentHp:maxHp,atk:fixed.atk,spd:fixed.spd,xp:fixed.xp,id:i}}
function beginMobBattle(){const a=stages[state.stage],count=Math.min(4,2+Math.floor(Math.random()*(state.stage>=2?3:2))),pool=[...a.enemies].sort(()=>Math.random()-.5);battle={enemies:Array.from({length:count},(_,i)=>makeEnemy(pool[i%pool.length],i,count)),boss:false,lost:false,guard:false};startBattle(`${count}体の モンスターが あらわれた！`)}
function beginMiniBoss(){const a=stages[state.stage],m=miniBosses[state.stage],lv=a.gate,maxHp=55+lv*8;battle={enemies:[{name:m.name,icon:m.icon,lv,maxHp,currentHp:maxHp,atk:6+lv*.95,spd:5+lv*1.25,xp:40+lv*10,id:0}],boss:false,miniBoss:true,lost:false,guard:false};startBattle(`ステージ小ボス・${m.name}が あらわれた！`)}
function beginBoss(type){if(type==='mayu'){battle={enemies:[{name:'まゆ',image:'assets/mayu-title-v2.png',lv:5,maxHp:500,currentHp:500,atk:13,spd:15,xp:180,id:0,bigMove:'レポート大旋風'}],boss:'mayu',lost:false,guard:false};startBattle('中ボス・まゆが あらわれた！')}else{battle={enemies:[{name:'こうき',image:'assets/kouki-upper-body-v1.png',lv:50,maxHp:5000,currentHp:5000,atk:72,spd:78,xp:2500,id:0,bigMove:'受験プレッシャー砲'}],boss:'kouki',lost:false,guard:false};startBattle('大ボス・こうきが あらわれた！')}}
function startBattle(text){busy=false;battle.selectedId=battle.enemies[0].id;if(battle.boss&&!Number.isFinite(battle.bossCharge))battle.bossCharge=0;show('#battleScreen');$('#battleLog').textContent=text+' 敵をタップして狙おう！';renderEnemies();updateBattle();previewTurnOrder();toggleCommands(true);beep(battle.boss?170:260,.13)}
function aliveEnemies(){return battle.enemies.filter(e=>e.currentHp>0)}
function activeEnemy(){const alive=aliveEnemies();let e=alive.find(x=>x.id===battle.selectedId);if(!e&&alive.length){e=alive[0];battle.selectedId=e.id}return e}
function selectEnemy(id){if(busy)return;battle.selectedId=id;renderEnemies();updateBattle();const e=activeEnemy();log(`${e.name}を ねらっている！\nすばやさ ${Math.round(e.spd)}`);beep(410)}
function enemyMarkup(e,effects){const hp=Math.max(0,e.currentHp),pct=Math.max(0,hp/e.maxHp*100),avatar=e.image?`<img src="${e.image}" alt="">`:`<span>${e.icon}</span>`,stun=e.stunTurns?`<i class="ailment">行動不能${e.stunTurns}</i>`:'';return`<div class="enemy-mini-hp"><div><i style="width:${pct}%"></i></div><b>${hp}/${e.maxHp}</b></div>${avatar}<small>${e.name}<i>速${Math.round(e.spd)}</i>${effects}${stun}</small>`}
function renderEnemies(){const alive=aliveEnemies(),wrap=$('#enemySprite'),selected=activeEnemy();wrap.innerHTML='';alive.forEach(e=>{const el=document.createElement('button'),effects=`${e.bleedTurns?`<i class="ailment">出血${e.bleedTurns}</i>`:''}${e.attackDownTurns?`<i class="ailment">攻↓${e.attackDownTurns}</i>`:''}`;el.type='button';el.dataset.id=e.id;el.className='enemy-unit'+(e.id===selected.id?' target':'')+(e.enraged?' enraged':'');el.setAttribute('aria-label',`${e.name}を狙う。HP${Math.max(0,e.currentHp)}/${e.maxHp}、レベル${e.lv}、すばやさ${Math.round(e.spd)}`);el.innerHTML=enemyMarkup(e,effects);el.onclick=()=>selectEnemy(e.id);wrap.appendChild(el)});$('#enemyName').textContent=battle.boss?selected.name:`選択：${selected.name}`;$('#enemyLevel').textContent=`LV ${selected.lv}・速 ${Math.round(selected.spd)}`;$('#enemyHpBar').style.width=`${selected.currentHp/selected.maxHp*100}%`}
function updateMiniHp(){aliveEnemies().forEach(e=>{const unit=document.querySelector(`.enemy-unit[data-id="${e.id}"]`);if(!unit)return;const hp=Math.max(0,e.currentHp),bar=unit.querySelector('.enemy-mini-hp i'),text=unit.querySelector('.enemy-mini-hp b');if(bar)bar.style.width=`${Math.max(0,hp/e.maxHp*100)}%`;if(text)text.textContent=`${hp}/${e.maxHp}`})}
function updateBattle(){const s=stats(),e=activeEnemy();$('#battleLevel').textContent=state.level;$('#battleSpeed').textContent=Math.round(s.spd);$('#battleHp').textContent=`${Math.max(0,state.hp)}/${s.maxHp}`;$('#battleMp').textContent=`${state.mp}/${s.maxMp}`;$('#heroHpBar').style.width=`${Math.max(0,state.hp/s.maxHp*100)}%`;$('#heroMpBar').style.width=`${state.mp/s.maxMp*100}%`;if(e)$('#enemyHpBar').style.width=`${Math.max(0,e.currentHp/e.maxHp*100)}%`;updateMiniHp();updateBossGauge();updateSkillUnlocks();$('#carrotCount').textContent=`×${state.carrots}`;$('#waterCount').textContent=`×${state.waters}`}
function updateSkillUnlocks(){[['tail',3],['dig',5],['snack',8],['tackle',12],['father',18],['motherSupport',25],['rampage',35],['supreme',50]].forEach(([id,lv])=>$(`#${id}SkillBtn`).classList.toggle('hidden',state.level<lv))}
function updateBossGauge(){const gauge=$('#bossGauge');gauge.classList.toggle('hidden',!battle.boss);if(!battle.boss)return;const charge=Math.min(3,battle.bossCharge||0),ready=charge>=3;$('#bossGaugeBar').style.width=`${charge/3*100}%`;$('#bossGaugeText').textContent=ready?'READY!':`${charge}/3`;gauge.classList.toggle('ready',ready)}
function makeTurnOrder(heroSpeed=stats().spd){return[{kind:'hero',spd:heroSpeed},...aliveEnemies().map(e=>({kind:'enemy',spd:e.spd,enemy:e}))].sort((a,b)=>b.spd-a.spd||Math.random()-.5)}
function renderTurnMeter(order,current=-1){const meter=$('#turnMeter');meter.innerHTML='';order.forEach((turn,i)=>{const chip=document.createElement('span'),hero=turn.kind==='hero',dead=!hero&&turn.enemy.currentHp<=0;chip.className=`turn-chip${hero?' hero':''}${i<current?' done':''}${i===current?' active':''}${dead?' defeated':''}`;chip.innerHTML=`<b>${hero?'🐶 たると':`${turn.enemy.icon||'👤'} ${turn.enemy.name}`}</b><small>速 ${Math.round(turn.spd)}</small>`;meter.appendChild(chip)});const active=meter.querySelector('.active');if(active)active.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})}
function previewTurnOrder(){renderTurnMeter(makeTurnOrder())}
function toggleCommands(on){$$('#commands button,#skillMenu button,#healMenu button').forEach(b=>b.disabled=!on);busy=!on}
function openSkills(){if(busy)return;$('#commands').classList.add('hidden');$('#skillMenu').classList.remove('hidden');log('どの 必殺技を つかう？')}
function closeSkills(){$('#skillMenu').classList.add('hidden');$('#commands').classList.remove('hidden')}
function openHeals(){if(busy)return;$('#commands').classList.add('hidden');$('#healMenu').classList.remove('hidden');log('どうやって かいふくする？')}
function closeHeals(){$('#healMenu').classList.add('hidden');$('#commands').classList.remove('hidden')}
function closeMenus(){$('#skillMenu').classList.add('hidden');$('#healMenu').classList.add('hidden');$('#commands').classList.remove('hidden')}
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function act(type){if(busy)return;const s=stats(),skill=skills[type];if(skill&&state.mp<skill.mp){log(`${skill.name}を使うMPが たりない！`);return}if(type==='item'&&state.carrots<1){log('にんじんを もっていない！');return}if(type==='item'&&state.hp>=s.maxHp){log('HPは まんたんだ！');return}if(type==='water'&&state.waters<1){log('お水は もう残っていない！');return}if(type==='water'&&state.mp>=s.maxMp){log('MPは まんたんだ！');return}if(type==='mother'&&state.hp>=s.maxHp){log('HPは まんたんだ！');return}closeMenus();toggleCommands(false);battle.guard=false;
  const heroSpeed=s.spd+(skill?skill.speed:0),order=makeTurnOrder(heroSpeed);
  renderTurnMeter(order,0);log(`行動順：${order.map(x=>x.kind==='hero'?'たると':x.enemy.name).join(' → ')}`);await wait(600);
  for(let turnIndex=0;turnIndex<order.length;turnIndex++){const turn=order[turnIndex];renderTurnMeter(order,turnIndex);
    if(state.hp<=0||!aliveEnemies().length)break;
    if(turn.kind==='hero')await heroAction(type,s);else if(turn.enemy.currentHp>0)await enemyAction(turn.enemy,s);
  }
  if(state.hp>0&&aliveEnemies().length)await applyBleeding(s);battle.guard=false;if(state.hp<=0){lose();return}if(!aliveEnemies().length){if(await tryKoukiRevival()){toggleCommands(true);return}win();return}renderEnemies();updateBattle();previewTurnOrder();toggleCommands(true)}
async function heroAction(type,s){const target=activeEnemy();let text='';
  if(type==='attack'){const dmg=Math.max(2,Math.round(s.atk*(.85+Math.random()*.3)));target.currentHp-=dmg;showNumber(dmg,'damage',target);text=`たるとの こうげき！\n${target.name}に ${dmg}ダメージ！`;hitEnemies(false);beep(520)}
  if(type==='spin'){state.mp-=skills.spin.mp;target.stunTurns=2;text=`たるとの くるん！\n${target.name}は目を回した！ 2回行動不能！`;hitEnemies(false);beep(760,.12)}
  if(type==='bite'){state.mp-=skills.bite.mp;const dmg=Math.max(4,Math.round(s.atk*2));target.currentHp-=dmg;target.bleedTurns=3;target.bleedPower=Math.max(2,Math.round(s.atk*.35));showNumber(dmg,'damage',target);text=`たるとの かみつき！\n${target.name}に ${dmg}ダメージ＋出血！`;hitEnemies(false);beep(430,.14)}
  if(type==='bark'){state.mp-=skills.bark.mp;aliveEnemies().forEach(e=>e.attackDownTurns=Math.max(e.attackDownTurns||0,2));text=`たるとは 大きく吠えた！\n敵全体の攻撃力が 2ターン低下！`;hitEnemies(true);beep(860,.18)}
  if(type==='tail'){state.mp-=skills.tail.mp;let total=0;aliveEnemies().forEach(e=>{const dmg=Math.max(2,Math.round(s.atk*(.85+Math.random()*.3)));e.currentHp-=dmg;total+=dmg;showNumber(dmg,'damage',e)});text=`たるとは しっぽを振り回した！\n敵全体に攻撃！ 合計${total}ダメージ！`;hitEnemies(true);beep(610,.16)}
  if(type==='water'){state.waters--;const restored=s.maxMp-state.mp;state.mp=s.maxMp;showNumber(restored,'mp');text=`たるとは お水を飲んだ！\nMPが ${restored}かいふく！ 全回復！`;beep(680,.16)}
  if(type==='mother'){state.mp-=skills.mother.mp;const heal=s.maxHp-state.hp;state.hp=s.maxHp;showNumber(heal,'heal');text=`かーちゃんが なでなでしてくれた！\nHPが ${heal}かいふく！ 全回復！`;beep(920,.2)}
  if(type==='guard'){battle.guard=true;state.mp=Math.min(s.maxMp,state.mp+3);text='たるとは 身をまもった！\nこの後のダメージを軽減！';beep(340)}
  if(type==='item'){state.carrots--;const before=state.hp;state.hp=Math.min(s.maxHp,state.hp+Math.round(s.maxHp*.5));const heal=state.hp-before;showNumber(heal,'heal');text=`にんじんを たべた！\nHPが ${heal}かいふく！`;beep(690)}
  log(text);updateBattle();await wait(620);const defeated=battle.enemies.filter(e=>e.currentHp<=0&&!e.counted);defeated.forEach(e=>e.counted=true);if(defeated.length&&aliveEnemies().length){renderEnemies();log(`${defeated.length}体を たおした！ 残り ${aliveEnemies().length}体！`);await wait(420)}}
async function enemyAction(enemy,s){const weakened=enemy.attackDownTurns>0,meterBig=Boolean(battle.boss&&enemy.bigMove&&battle.bossCharge>=3),randomBig=Boolean(battle.boss&&enemy.bigMove&&!meterBig&&Math.random()<.25),big=meterBig||randomBig,power=big?1.8:1,attack=enemy.atk*(weakened?0.55:1)*power;let dmg=Math.max(1,Math.round(attack-s.def*.65+Math.random()*3-1));if(battle.guard)dmg=Math.max(1,Math.floor(dmg*.3));state.hp-=dmg;if(weakened)enemy.attackDownTurns--;if(battle.boss){if(meterBig)battle.bossCharge=0;else if(!randomBig)battle.bossCharge=Math.min(3,battle.bossCharge+1)}showNumber(dmg,big?'critical':'damage');const bigReason=meterBig?'ゲージ満タン！':'不意打ち！';log(big?`⚠ ${bigReason} ${enemy.name}の大技！ ${enemy.bigMove}！${weakened?'（攻撃力ダウン中）':''}\nたるとは ${dmg}の大ダメージ！${randomBig?' ゲージはそのまま！':''}`:`${enemy.name}の こうげき！${weakened?'（攻撃力ダウン中）':''}\nたるとは ${dmg}ダメージ！${battle.boss?' 大技ゲージ＋1！':''}`);$('#heroSprite').classList.add(big?'boss-hit':'hero-hit');beep(big?75:120,big?0.2:0.09);updateBattle();await wait(big?720:430);$('#heroSprite').classList.remove('hero-hit','boss-hit')}
async function tryKoukiRevival(){if(battle.boss!=='kouki'||battle.koukiRevived)return false;battle.koukiRevived=true;log('こうきを倒した……！');await wait(800);const banner=document.createElement('div');banner.className='revival-banner';banner.innerHTML='<small>FINAL BOSS REVIVAL</small><strong>こうき、復活！</strong><span>「ここからが本気だ！」</span>';$('#battleScreen').appendChild(banner);beep(65,.5);await wait(1100);const e=battle.enemies[0];e.name='本気のこうき';e.enraged=true;e.maxHp=8000;e.currentHp=e.maxHp;e.atk=Math.round(e.atk*1.35);e.spd+=12;e.xp=3500;e.bigMove='超・受験プレッシャー砲';e.bleedTurns=0;e.attackDownTurns=0;battle.bossCharge=0;battle.selectedId=e.id;renderEnemies();updateBattle();previewTurnOrder();log('本気のこうきが立ちはだかった！\nHP・攻撃力・すばやさが大幅アップ！');setTimeout(()=>banner.remove(),900);await wait(700);return true}
async function applyBleeding(s){const bleeding=aliveEnemies().filter(e=>e.bleedTurns>0);if(!bleeding.length)return;let total=0;bleeding.forEach(e=>{const dmg=Math.min(e.currentHp,e.bleedPower||2);e.currentHp-=dmg;e.bleedTurns--;total+=dmg;showNumber(dmg,'bleed',e)});log(`出血の追加ダメージ！\n合計 ${total}ダメージ！`);updateBattle();await wait(650)}
function showNumber(value,kind='damage',enemy=null){const host=enemy?document.querySelector(`.enemy-unit[data-id="${enemy.id}"]`):$('.hero-area');if(!host)return;const pop=document.createElement('span');pop.className=`damage-pop ${kind}`;pop.textContent=`${kind==='heal'||kind==='mp'?'+':'−'}${Math.max(0,Math.round(value))}${kind==='mp'?' MP':''}`;host.appendChild(pop);setTimeout(()=>pop.remove(),950)}
function log(t){$('#battleLog').innerText=t}
function hitEnemies(all){const units=all?$$('.enemy-unit'):[$('.enemy-unit.target')];units.filter(Boolean).forEach(el=>{el.classList.remove('enemy-hit');void el.offsetWidth;el.classList.add('enemy-hit')});const ef=$('#effect');ef.textContent=all?'🌀':'⚔';ef.classList.remove('skill-flash');void ef.offsetWidth;ef.classList.add('skill-flash');setTimeout(()=>ef.textContent='',450)}
function addExp(amount){const beforeLevel=state.level,beforeStats=stats(beforeLevel);let levels=0;state.exp+=amount;while(state.level<MAX_LEVEL){const need=expForNext(state.level);if(state.exp<need)break;state.exp-=need;state.level++;levels++}if(state.level>=MAX_LEVEL)state.exp=0;if(levels){pendingLevelDetails={beforeLevel,afterLevel:state.level,before:beforeStats,after:stats(state.level)};setTimeout(showLevelStatus,120)}return levels}
function win(){battle.lost=false;const xp=battle.enemies.reduce((n,e)=>n+e.xp,0),levels=addExp(xp),s=stats();state.totalWins++;state.score+=xp*10+Math.max(0,state.hp)*3;if(battle.miniBoss){state.miniBossDefeated=true;if(!stages[state.stage].boss){battle.stageAdvanced=true;state.stage++;state.areaWins=0;state.miniBossDefeated=false;state.carrots=Math.min(5,state.carrots+1)}}else if(battle.boss==='mayu'){state.stage++;state.areaWins=0;state.miniBossDefeated=false;state.carrots=5}else if(battle.boss==='kouki'){state.finished=true}else state.areaWins++;if(levels){state.hp=s.maxHp;state.mp=s.maxMp;state.waters=3;state.carrots=Math.min(5,state.carrots+1)}else state.mp=Math.min(s.maxMp,state.mp+4);save();show('#resultScreen');$('#resultKicker').textContent=battle.miniBoss?'STAGE BOSS DEFEATED!':battle.boss?'BOSS DEFEATED!':'VICTORY!';$('#resultIcon').textContent=battle.miniBoss?'⭐':battle.boss?'👑':'🏆';$('#resultTitle').textContent=battle.miniBoss?`${battle.enemies[0].name}を倒した！`:battle.boss==='mayu'?'まゆに勝った！':battle.boss==='kouki'?'こうきを倒した！':`${battle.enemies.length}体を倒した！`;$('#resultText').innerHTML=`経験値 <b>${xp}</b> を てにいれた！<br>${battle.miniBoss?'ステージの小ボスを撃破！':'たるとは レベル'+state.level+'。'}${levels?'<br>お水の回数が3回に戻った！':''}`;$('#levelUp').classList.toggle('hidden',!levels);$('#levelUp').textContent=levels?`LEVEL UP!　${levels>1?'×'+levels:''}`:'LEVEL UP!';$('#resultBtn').textContent=state.finished?'エンディングへ':'冒険をつづける';beep(880,.18)}
function lose(){battle.lost=true;try{localStorage.removeItem(SAVE_KEY)}catch(_){}show('#resultScreen');$('#resultKicker').textContent='GAME OVER';$('#resultIcon').textContent='💫';$('#resultTitle').textContent='たるとは力つきた…';$('#resultText').innerHTML='レベルと冒険の記録は失われました。<br>レベル1から再出発しよう！';$('#levelUp').classList.add('hidden');$('#resultBtn').textContent='レベル1からやり直す'}
function afterResult(){if(battle.lost){state=fresh();save();showMap('勇者たるとの冒険が、もう一度はじまる！');return}if(state.finished){ending();return}if(battle.miniBoss){showMap(battle.stageAdvanced?'小ボスを倒してステージクリア！ 新しい場所へ進もう！':'小ボスを撃破！ この先に本当のボスが待っている！');return}showMap(battle.boss==='mayu'?'まゆを倒し、新しい道がひらいた！':undefined)}
function ending(){show('#endingScreen');$('#endLevel').textContent=state.level;$('#endWins').textContent=state.totalWins;const total=state.score+state.level*2000+state.carrots*500;$('#endScore').textContent=total.toLocaleString('ja-JP');try{const best=Number(localStorage.getItem(SCORE_KEY))||0;if(total>best)localStorage.setItem(SCORE_KEY,String(total));localStorage.removeItem(SAVE_KEY)}catch(_){}beep(990,.25)}
$('#newGameBtn').onclick=startNew;$('#continueBtn').onclick=continueGame;$('#fullscreenBtn').onclick=enterFullscreen;$('#advanceBtn').onclick=advance;$('#restBtn').onclick=rest;$('#resultBtn').onclick=afterResult;$('#endingHomeBtn').onclick=()=>location.href='index.html';$('#endingAgainBtn').onclick=startNew;$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♪':'×'};$('#skillsBtn').onclick=openSkills;$('#skillBackBtn').onclick=closeSkills;$('#healsBtn').onclick=openHeals;$('#healBackBtn').onclick=closeHeals;$$('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));$$('[data-skill]').forEach(b=>b.onclick=()=>act(b.dataset.skill));$$('[data-heal]').forEach(b=>b.onclick=()=>act(b.dataset.heal));
const showMapWithoutMusic=showMap;
showMap=function(custom){playMusic('map');return showMapWithoutMusic(custom)};
const startBattleWithoutMusic=startBattle;
startBattle=function(text){const key=battle.miniBoss?'miniboss':battle.boss==='mayu'?'mayu':battle.boss==='kouki'?'kouki1':'regular';playMusic(key,true);return startBattleWithoutMusic(text)};
const reviveWithoutMusic=tryKoukiRevival;
tryKoukiRevival=async function(){if(battle&&battle.boss==='kouki'&&!battle.koukiRevived)playMusic('kouki2',true);return reviveWithoutMusic()};
const winWithoutMusic=win;
win=function(){playMusic('victory',true);return winWithoutMusic()};
const loseWithoutMusic=lose;
lose=function(){playMusic('title',true);return loseWithoutMusic()};
const endingWithoutMusic=ending;
ending=function(){playMusic('victory',true);return endingWithoutMusic()};
$('#soundBtn').onclick=()=>{sound=!sound;$('#soundBtn').textContent=sound?'♪':'×';if(sound)playMusic(currentMusicKey);else pauseMusic()};

const rouletteMaps=[
  {name:'まゆへの草原ロード',chapter:'MAP 1・MAYU ROUTE',boss:'mayu',stage:0,squares:['start','battle','heal','damage','xp','battle','mini','battle','damage','heal','xp','battle','mini','battle','boss']},
  {name:'こうきの最終試験ロード',chapter:'MAP 2・KOUKI ROUTE',boss:'kouki',stage:5,squares:['start','battle','xp','damage','mini','heal','battle','xp','battle','damage','mini','xp','heal','battle','damage','xp','mini','battle','heal','boss']}
];
const squareInfo={start:['🏠','スタート'],battle:['⚔','敵マス'],mini:['🐾','小ボスマス'],damage:['💥','ダメージマス'],heal:['💚','回復マス'],xp:['⭐','経験値マス'],boss:['👑','ボスマス']};
let rouletteBusy=false;
function normalizeBoardState(){if(!Number.isFinite(state.board))state.board=state.stage>=1?1:0;if(!Number.isFinite(state.boardPos))state.boardPos=0;state.board=Math.min(1,state.board);state.stage=rouletteMaps[state.board].stage}
function renderBoardNodes(){const map=rouletteMaps[state.board],wrap=$('#mapNodes');wrap.innerHTML='';map.squares.forEach((type,index)=>{const node=document.createElement('span'),info=squareInfo[type];node.className=`map-node ${type}${index===state.boardPos?' current':''}`;node.innerHTML=`<b>${info[0]}</b><small>${index}</small>`;node.setAttribute('aria-label',`${index}マス目 ${info[1]}`);if(index===state.boardPos){const token=document.createElement('img');token.className='board-token';token.src='assets/taruto-card-v1.png';token.alt='現在地・たると';node.appendChild(token)}wrap.appendChild(node)})}
function showBoardMap(custom){normalizeBoardState();playMusic('map');show('#mapScreen');const map=rouletteMaps[state.board],s=stats(),remaining=map.squares.length-1-state.boardPos;renderBoardNodes();$('#mapBackdrop').classList.toggle('final-map',state.board===1);$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=map.chapter;$('#locationName').textContent=map.name;$('#mapMessage').textContent=custom||`${map.boss==='mayu'?'中ボス・まゆ':'大ボス・こうき'}のマスに ぴったり止まろう！`;$('#goalDistance').textContent=remaining?`ボスまで あと${remaining}マス`:'ボスマスに到着！';$('#advanceBtn').textContent=remaining?'ルーレットを回す！':`${map.boss==='mayu'?'まゆ':'こうき'}に挑む！`;$('#advanceBtn').disabled=false;rouletteBusy=false;save()}
showMap=showBoardMap;
function xpForBoardLevels(count){let lv=state.level,total=0;for(let i=0;i<count&&lv<MAX_LEVEL;i++,lv++)total+=expForNext(lv);return total}
async function rollRoulette(){if(rouletteBusy)return;normalizeBoardState();const map=rouletteMaps[state.board],goal=map.squares.length-1;if(state.boardPos===goal){startBoardBoss();return}rouletteBusy=true;$('#advanceBtn').disabled=true;const display=$('#rouletteNumber');display.classList.add('spinning');let result=1;for(let i=0;i<13;i++){result=1+Math.floor(Math.random()*6);display.textContent=result;beep(300+i*24,.035);await wait(65+i*5)}display.classList.remove('spinning');const remaining=goal-state.boardPos;if(result>remaining){rouletteBusy=false;$('#advanceBtn').disabled=false;$('#mapMessage').textContent=`${result}！ ゴールまであと${remaining}マス。ぴったりではないので、その場にとどまった！`;beep(145,.18);save();return}state.boardPos+=result;renderBoardNodes();$('#goalDistance').textContent=state.boardPos===goal?'ボスマスに到着！':`ボスまで あと${goal-state.boardPos}マス`;save();await wait(650);await resolveBoardSquare(map.squares[state.boardPos])}
async function resolveBoardSquare(type){if(type==='battle'){beginMobBattle();battle.boardBattle=true;battle.boardKind='battle';return}if(type==='mini'){beginBoardMini();return}if(type==='boss'){startBoardBoss();return}const s=stats();if(type==='damage'){const damage=Math.max(3,Math.round(s.maxHp*(state.board?0.24:0.16)));state.hp=Math.max(1,state.hp-damage);showBoardMap(`💥 落とし穴！ HPが ${damage}減った！`);beep(110,.18);return}if(type==='heal'){const hpBefore=state.hp,mpBefore=state.mp;state.hp=Math.min(s.maxHp,state.hp+Math.round(s.maxHp*.45));state.mp=Math.min(s.maxMp,state.mp+Math.round(s.maxMp*.35));showBoardMap(`💚 いやしの泉！ HP＋${state.hp-hpBefore}、MP＋${state.mp-mpBefore}！`);beep(720,.18);return}if(type==='xp'){const amount=xpForBoardLevels(state.board?9:2),levels=addExp(amount),newStats=stats();if(levels){state.hp=newStats.maxHp;state.mp=newStats.maxMp;state.waters=3}showBoardMap(`⭐ 経験値 ${amount}！ レベルが ${levels}上がった！`);beep(900,.2);return}showBoardMap()}
function beginBoardMini(){const index=state.board?5:0,m=miniBosses[index],lv=Math.min(MAX_LEVEL,state.level+2),maxHp=55+lv*8;battle={enemies:[{name:m.name,icon:m.icon,lv,maxHp,currentHp:maxHp,atk:6+lv*.95,spd:5+lv*1.25,xp:40+lv*10,id:0}],boss:false,miniBoss:true,boardBattle:true,boardKind:'mini',lost:false,guard:false};startBattle(`小ボス・${m.name}が あらわれた！`)}
function startBoardBoss(){const map=rouletteMaps[state.board];beginBoss(map.boss);battle.boardBattle=true;battle.boardKind='boss'}
function boardWin(){playMusic('victory',true);battle.lost=false;const xp=battle.enemies.reduce((sum,e)=>sum+e.xp,0),levels=addExp(xp),newStats=stats();state.totalWins++;state.score+=xp*10+Math.max(0,state.hp)*3;if(levels){state.hp=newStats.maxHp;state.mp=newStats.maxMp;state.waters=3;state.carrots=Math.min(5,state.carrots+1)}else state.mp=Math.min(newStats.maxMp,state.mp+4);if(battle.boardKind==='boss'){if(battle.boss==='mayu'){state.board=1;state.boardPos=0;state.stage=5;state.carrots=5;state.pendingMapMessage='まゆを倒した！ こうきへ続く最終マップが現れた！'}else{state.finished=true}}else state.pendingMapMessage=battle.boardKind==='mini'?'小ボスを撃破！ 同じマスからルーレットを続けよう！':'敵を倒した！ 同じマスからルーレットを続けよう！';save();show('#resultScreen');$('#resultKicker').textContent=battle.boardKind==='boss'?'BOSS DEFEATED!':battle.boardKind==='mini'?'MINI BOSS DEFEATED!':'VICTORY!';$('#resultIcon').textContent=battle.boardKind==='boss'?'👑':battle.boardKind==='mini'?'🐾':'🏆';$('#resultTitle').textContent=battle.boss==='mayu'?'まゆに勝った！':battle.boss==='kouki'?'こうきを倒した！':`${battle.enemies.length}体を倒した！`;$('#resultText').innerHTML=`経験値 <b>${xp}</b> を てにいれた！<br>たるとは レベル${state.level}。${levels?'<br>お水の回数が3回に戻った！':''}`;$('#levelUp').classList.toggle('hidden',!levels);$('#levelUp').textContent=levels?`LEVEL UP!　${levels>1?'×'+levels:''}`:'LEVEL UP!';$('#resultBtn').textContent=state.finished?'エンディングへ':'すごろくへ戻る';beep(880,.18)}
const winBeforeBoard=win;
win=function(){if(battle&&battle.boardBattle)return boardWin();return winBeforeBoard()};
const resultBeforeBoard=afterResult;
function boardAfterResult(){if(!battle||!battle.boardBattle)return resultBeforeBoard();if(battle.lost){state=fresh();showBoardMap('勇者たるとの冒険が、もう一度はじまる！');return}if(state.finished){ending();return}const message=state.pendingMapMessage;delete state.pendingMapMessage;showBoardMap(message)}
$('#advanceBtn').onclick=rollRoulette;
$('#resultBtn').onclick=boardAfterResult;

function buildPathMap(name,chapter,boss,stage,total,branches){const nodes={};const inBranchDistance=d=>branches.find(b=>d>b.at&&d<b.rejoin);for(let d=0;d<=total;d++){const branch=branches.find(b=>b.at===d),inside=inBranchDistance(d);if(inside){['u','l'].forEach(lane=>{const id=`${d}${lane}`,type=lane==='u'?(d%2?'xp':'heal'):(d%2?'battle':'damage');nodes[id]={id,d,lane,type,x:60+d*105,y:lane==='u'?78:222,next:[]}})}else{const id=`${d}c`,type=d===0?'start':d===total?'boss':branch?'branch':d%7===0?'mini':d%5===0?'heal':d%4===0?'xp':d%3===0?'damage':'battle';nodes[id]={id,d,lane:'c',type,x:60+d*105,y:150,next:[]}}}Object.values(nodes).forEach(node=>{if(node.d===total)return;const branch=branches.find(b=>b.at===node.d);if(branch){node.next=[`${node.d+1}u`,`${node.d+1}l`];return}const rejoin=branches.find(b=>b.rejoin===node.d+1);if(rejoin&&node.lane!=='c'){node.next=[`${node.d+1}c`];return}const nextLane=inBranchDistance(node.d+1)?node.lane:'c';node.next=[`${node.d+1}${nextLane}`]});return{name,chapter,boss,stage,total,nodes,start:'0c'}}
const pathMaps=[buildPathMap('まゆへの草原ロード','MAP 1・MAYU ROUTE','mayu',0,18,[{at:4,rejoin:7},{at:11,rejoin:14}]),buildPathMap('こうきの最終試験ロード','MAP 2・KOUKI ROUTE','kouki',5,24,[{at:5,rejoin:8},{at:13,rejoin:16}])];
function normalizePathState(){if(!Number.isFinite(state.board))state.board=0;state.board=Math.min(1,state.board);const map=pathMaps[state.board];if(!state.boardNode||!map.nodes[state.boardNode])state.boardNode=map.start;state.stage=map.stage;state.boardPos=map.nodes[state.boardNode].d}
function addRouteLine(wrap,a,b){const dx=b.x-a.x,dy=b.y-a.y,line=document.createElement('i');line.className='route-line';line.style.left=`${a.x}px`;line.style.top=`${a.y}px`;line.style.width=`${Math.hypot(dx,dy)}px`;line.style.transform=`rotate(${Math.atan2(dy,dx)}rad)`;wrap.appendChild(line)}
function renderPathNodes(walking=false){normalizePathState();const map=pathMaps[state.board],wrap=$('#mapNodes');wrap.className='map-nodes path-board';wrap.style.width=`${map.total*105+120}px`;wrap.innerHTML='';Object.values(map.nodes).forEach(node=>node.next.forEach(next=>addRouteLine(wrap,node,map.nodes[next])));Object.values(map.nodes).forEach(node=>{const info=squareInfo[node.type]||['🔀','分岐'],el=document.createElement('span');el.className=`map-node ${node.type}${node.id===state.boardNode?' current':''}${node.d<map.nodes[state.boardNode].d?' visited':''}`;el.dataset.node=node.id;el.style.left=`${node.x}px`;el.style.top=`${node.y}px`;el.innerHTML=`<b>${info[0]}</b><small>${node.d}</small>`;if(node.id===state.boardNode){const token=document.createElement('img');token.className=`board-token${walking?' walking':''}`;token.src='assets/taruto-card-v1.png';token.alt='現在地・たると';el.appendChild(token)}wrap.appendChild(el)});requestAnimationFrame(()=>{const current=wrap.querySelector('.current');if(current)current.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})})}
function showPathMap(custom){normalizePathState();playMusic('map');show('#mapScreen');const map=pathMaps[state.board],node=map.nodes[state.boardNode],s=stats(),remaining=map.total-node.d;renderPathNodes();$('#mapBackdrop').classList.toggle('final-map',state.board===1);$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=map.chapter;$('#locationName').textContent=map.name;$('#mapMessage').textContent=custom||`${map.boss==='mayu'?'中ボス・まゆ':'大ボス・こうき'}へ向かって、1マスずつ進もう！`;$('#goalDistance').textContent=remaining?`ボスまで あと${remaining}マス`:'ボスマスに到着！';$('#advanceBtn').textContent=remaining?'ルーレットを回す！':'ボスへの挑戦を選ぶ';$('#advanceBtn').disabled=false;rouletteBusy=false;save()}
showMap=showPathMap;
function openRouteChoice(){return new Promise(resolve=>{$('#choiceKicker').textContent='ROUTE SELECT';$('#choiceTitle').textContent='どちらへ進む？';$('#choiceText').textContent='上は回復・経験値が多め。下は戦闘・危険マスが多め！';$('#routeChoices').classList.remove('hidden');$('#bossChoices').classList.add('hidden');$('#mapChoice').classList.remove('hidden');$('#upperRouteBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');resolve('u')};$('#lowerRouteBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');resolve('l')}})}
function openBossChoice(){const map=pathMaps[state.board];$('#choiceKicker').textContent='BOSS SQUARE';$('#choiceTitle').textContent=`${map.boss==='mayu'?'まゆ':'こうき'}のマスに到着！`;$('#choiceText').textContent='今すぐ戦う？ それともスタートへ戻ってレベルを上げる？';$('#routeChoices').classList.add('hidden');$('#bossChoices').classList.remove('hidden');$('#mapChoice').classList.remove('hidden');$('#fightBossBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');startPathBoss()};$('#returnStartBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');state.boardNode=map.start;state.boardPos=0;delete state.pendingNext;showPathMap('レベルと持ち物を保ったまま、スタートへ戻った！')}}
function chooseNextNode(map,node,lane){if(node.next.length<2)return node.next[0];return node.next.find(id=>id.endsWith(lane))||node.next[0]}
async function rollPathRoulette(){if(rouletteBusy)return;normalizePathState();const map=pathMaps[state.board],startNode=map.nodes[state.boardNode],remaining=map.total-startNode.d;if(!remaining){openBossChoice();return}rouletteBusy=true;$('#advanceBtn').disabled=true;const display=$('#rouletteNumber');display.classList.add('spinning');let result=1;for(let i=0;i<13;i++){result=1+Math.floor(Math.random()*6);display.textContent=result;beep(300+i*24,.035);await wait(65+i*5)}display.classList.remove('spinning');if(result>remaining){rouletteBusy=false;$('#advanceBtn').disabled=false;$('#mapMessage').textContent=`${result}！ ボスまであと${remaining}マス。ぴったりではないので、その場にとどまった！`;beep(145,.18);return}for(let step=0;step<result;step++){let node=map.nodes[state.boardNode],next;if(node.next.length>1){let lane=state.pendingNext;if(!lane)lane=await openRouteChoice();next=chooseNextNode(map,node,lane);delete state.pendingNext}else next=node.next[0];state.boardNode=next;state.boardPos=map.nodes[next].d;renderPathNodes(true);beep(420+step*25,.05);await wait(430)}renderPathNodes(false);save();const landed=map.nodes[state.boardNode];if(landed.type==='branch'){state.pendingNext=await openRouteChoice();showPathMap(`${state.pendingNext==='u'?'上':'下'}の道を選んだ！ 次のルーレットで進もう！`);return}await resolvePathSquare(landed.type)}
async function resolvePathSquare(type){if(type==='battle'){beginMobBattle();battle.boardBattle=true;battle.pathBoard=true;battle.boardKind='battle';return}if(type==='mini'){beginPathMini();return}if(type==='boss'){openBossChoice();return}const s=stats();if(type==='damage'){const damage=Math.max(3,Math.round(s.maxHp*(state.board?.24:.16)));state.hp=Math.max(1,state.hp-damage);showPathMap(`💥 危険なマス！ HPが ${damage}減った！`);beep(110,.18);return}if(type==='heal'){const beforeHp=state.hp,beforeMp=state.mp;state.hp=Math.min(s.maxHp,state.hp+Math.round(s.maxHp*.45));state.mp=Math.min(s.maxMp,state.mp+Math.round(s.maxMp*.35));showPathMap(`💚 回復マス！ HP＋${state.hp-beforeHp}、MP＋${state.mp-beforeMp}！`);beep(720,.18);return}if(type==='xp'){const amount=xpForBoardLevels(state.board?7:2),levels=addExp(amount),nextStats=stats();if(levels){state.hp=nextStats.maxHp;state.mp=nextStats.maxMp;state.waters=3}showPathMap(`⭐ 経験値 ${amount}！ レベルが ${levels}上がった！`);beep(900,.2);return}showPathMap()}
function beginPathMini(){const index=state.board?5:0,m=miniBosses[index],lv=Math.min(MAX_LEVEL,state.level+2),maxHp=55+lv*8;battle={enemies:[{name:m.name,icon:m.icon,lv,maxHp,currentHp:maxHp,atk:6+lv*.95,spd:5+lv*1.25,xp:40+lv*10,id:0}],boss:false,miniBoss:true,boardBattle:true,pathBoard:true,boardKind:'mini',lost:false,guard:false};startBattle(`小ボス・${m.name}が あらわれた！`)}
function startPathBoss(){const map=pathMaps[state.board];beginBoss(map.boss);battle.boardBattle=true;battle.pathBoard=true;battle.boardKind='boss'}
function pathWin(){playMusic('victory',true);battle.lost=false;const xp=battle.enemies.reduce((sum,e)=>sum+e.xp,0),levels=addExp(xp),newStats=stats();state.totalWins++;state.score+=xp*10+Math.max(0,state.hp)*3;if(levels){state.hp=newStats.maxHp;state.mp=newStats.maxMp;state.waters=3;state.carrots=Math.min(5,state.carrots+1)}else state.mp=Math.min(newStats.maxMp,state.mp+4);if(battle.boardKind==='boss'){if(battle.boss==='mayu'){state.board=1;state.boardNode=pathMaps[1].start;state.boardPos=0;state.stage=5;state.carrots=5;state.pendingMapMessage='まゆを倒した！ こうきへ続く最終マップが現れた！'}else state.finished=true}else state.pendingMapMessage=battle.boardKind==='mini'?'小ボスを撃破！ 止まったマスから再開！':'敵を倒した！ 止まったマスから再開！';save();show('#resultScreen');$('#resultKicker').textContent=battle.boardKind==='boss'?'BOSS DEFEATED!':battle.boardKind==='mini'?'MINI BOSS DEFEATED!':'VICTORY!';$('#resultIcon').textContent=battle.boardKind==='boss'?'👑':battle.boardKind==='mini'?'🐾':'🏆';$('#resultTitle').textContent=battle.boss==='mayu'?'まゆに勝った！':battle.boss==='kouki'?'こうきを倒した！':`${battle.enemies.length}体を倒した！`;$('#resultText').innerHTML=`経験値 <b>${xp}</b> を てにいれた！<br>たるとは レベル${state.level}。${levels?'<br>お水の回数が3回に戻った！':''}`;$('#levelUp').classList.toggle('hidden',!levels);$('#levelUp').textContent=levels?`LEVEL UP!　${levels>1?'×'+levels:''}`:'LEVEL UP!';$('#resultBtn').textContent=state.finished?'エンディングへ':'すごろくへ戻る';beep(880,.18)}
const winBeforePath=win;
win=function(){if(battle&&battle.pathBoard)return pathWin();return winBeforePath()};
function pathAfterResult(){if(!battle||!battle.pathBoard)return boardAfterResult();if(battle.lost){state=fresh();showPathMap('勇者たるとの冒険が、もう一度はじまる！');return}if(state.finished){ending();return}const message=state.pendingMapMessage;delete state.pendingMapMessage;showPathMap(message)}
$('#advanceBtn').onclick=rollPathRoulette;
$('#resultBtn').onclick=pathAfterResult;

function createRouteMapV2(name,chapter,boss,stage,hard=false){const base=[
  ['s',0,70,260,'start',['m1']],['m1',1,200,260,'battle',['m2']],['m2',2,330,260,'heal',['f1']],['f1',3,460,260,'branch',['t1','b1']],
  ['t1',4,590,150,hard?'battle':'xp',['t2']],['t2',5,720,85,'battle',['t3']],['t3',6,850,75,'heal',['t4']],['t4',7,980,105,'mini',['t5']],['t5',8,1110,150,'xp',['t6']],['t6',9,1240,205,'battle',['merge']],
  ['b1',4,590,360,'battle',['b2']],['b2',5,720,425,'damage',['f2']],['f2',6,850,390,'branch',['u1','l1']],
  ['u1',7,980,320,'heal',['u2']],['u2',8,1110,310,'xp',['u3']],['u3',9,1240,235,'battle',['merge']],
  ['l1',7,980,470,'damage',['l2']],['l2',8,1110,455,hard?'mini':'battle',['l3']],['l3',9,1240,350,'xp',['merge']],
  ['merge',10,1370,260,'heal',['e1']],['e1',11,1500,260,'mini',['e2']],['e2',12,1630,260,'battle',['boss']],['boss',13,1770,260,'boss',[]]
];const nodes=Object.fromEntries(base.map(([id,d,x,y,type,next])=>[id,{id,d,x,y,type,next}]));if(hard){nodes.m2.type='xp';nodes.t3.type='battle';nodes.merge.type='xp';nodes.u1.type='battle'}return{name,chapter,boss,stage,total:13,start:'s',nodes,width:1860}}
const routeMapsV2=[createRouteMapV2('まゆへの冒険ロード','MAP 1・MAYU ROUTE','mayu',0),createRouteMapV2('こうきの最終試験ロード','MAP 2・KOUKI ROUTE','kouki',5,true)];
function normalizeRouteV2(){if(!Number.isFinite(state.board))state.board=0;state.board=Math.min(1,state.board);const map=routeMapsV2[state.board];if(!state.routeNode||!map.nodes[state.routeNode])state.routeNode=map.start;state.stage=map.stage;state.boardPos=map.nodes[state.routeNode].d}
function renderRouteV2(walking=false){normalizeRouteV2();const map=routeMapsV2[state.board],wrap=$('#mapNodes'),scale=innerHeight<720?.75:1;wrap.className='map-nodes route-board-v2';wrap.style.width=`${map.width}px`;wrap.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','route-svg');svg.setAttribute('viewBox',`0 0 ${map.width} ${520*scale}`);Object.values(map.nodes).forEach(node=>node.next.forEach(id=>{const next=map.nodes[id],line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',node.x);line.setAttribute('y1',node.y*scale);line.setAttribute('x2',next.x);line.setAttribute('y2',next.y*scale);svg.appendChild(line)}));wrap.appendChild(svg);[['上ルート：回復・経験値多め',760,25],['下ルート：戦闘・危険多め',720,495]].forEach(([textValue,x,y])=>{const label=document.createElement('span');label.className='route-label';label.textContent=textValue;label.style.left=`${x}px`;label.style.top=`${y*scale}px`;wrap.appendChild(label)});const current=map.nodes[state.routeNode];Object.values(map.nodes).forEach(node=>{const info=squareInfo[node.type]||['🔀','分岐'],el=document.createElement('span');el.className=`map-node ${node.type}${node.id===state.routeNode?' current':''}${node.d<current.d?' visited':''}`;el.style.left=`${node.x}px`;el.style.top=`${node.y*scale}px`;el.innerHTML=`<b>${info[0]}</b><small>${node.d}</small>`;el.setAttribute('aria-label',`${node.d}マス目 ${info[1]}`);if(node.id===state.routeNode){const token=document.createElement('img');token.className=`board-token${walking?' walking':''}`;token.src='assets/taruto-card-v1.png';token.alt='現在地・たると';el.appendChild(token)}wrap.appendChild(el)});requestAnimationFrame(()=>{const currentElement=wrap.querySelector('.current');if(currentElement)currentElement.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'})})}
function showRouteMapV2(custom){normalizeRouteV2();playMusic('map');show('#mapScreen');const map=routeMapsV2[state.board],node=map.nodes[state.routeNode],s=stats(),remaining=map.total-node.d;renderRouteV2();$('#mapBackdrop').classList.toggle('final-map',state.board===1);$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=map.chapter;$('#locationName').textContent=map.name;$('#mapMessage').textContent=custom||'道は線でつながっている。分岐で好きなルートを選ぼう！';$('#goalDistance').textContent=remaining?`ボスまで あと${remaining}マス`:'ボスマスに到着！';$('#advanceBtn').textContent=remaining?'ルーレットを回す！':'ボスへの挑戦を選ぶ';$('#advanceBtn').disabled=false;rouletteBusy=false;save()}
showMap=showRouteMapV2;
function askRouteV2(node){return new Promise(resolve=>{$('#choiceKicker').textContent='ROUTE SELECT';$('#choiceTitle').textContent='進む道を選ぼう！';$('#choiceText').textContent=node.id==='f1'?'上は回復・経験値多め。下は戦闘・危険多め！':'内側は回復ルート。外側は危険だが経験値も狙える！';$('#routeChoices').classList.remove('hidden');$('#bossChoices').classList.add('hidden');$('#upperRouteBtn').textContent=node.id==='f1'?'🌤 上ルート':'💚 内側ルート';$('#lowerRouteBtn').textContent=node.id==='f1'?'🌲 下ルート':'🔥 外側ルート';$('#mapChoice').classList.remove('hidden');$('#upperRouteBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');resolve(node.next[0])};$('#lowerRouteBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');resolve(node.next[1])}})}
function askBossV2(){const map=routeMapsV2[state.board];$('#choiceKicker').textContent='BOSS SQUARE';$('#choiceTitle').textContent=`${map.boss==='mayu'?'まゆ':'こうき'}のマスに到着！`;$('#choiceText').textContent='戦うか、スタートへ戻ってレベルを上げるか選ぼう！';$('#routeChoices').classList.add('hidden');$('#bossChoices').classList.remove('hidden');$('#mapChoice').classList.remove('hidden');$('#fightBossBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');startBossV2()};$('#returnStartBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');state.routeNode=map.start;state.boardPos=0;delete state.routeNext;showRouteMapV2('レベルと持ち物を保ったまま、スタートへ戻った！')}}
async function rollRouteV2(){if(rouletteBusy)return;normalizeRouteV2();const map=routeMapsV2[state.board],current=map.nodes[state.routeNode],remaining=map.total-current.d;if(!remaining){askBossV2();return}rouletteBusy=true;$('#advanceBtn').disabled=true;const display=$('#rouletteNumber');display.classList.add('spinning');let result=1;for(let i=0;i<13;i++){result=1+Math.floor(Math.random()*6);display.textContent=result;beep(300+i*24,.035);await wait(65+i*5)}display.classList.remove('spinning');if(result>remaining){rouletteBusy=false;$('#advanceBtn').disabled=false;$('#mapMessage').textContent=`${result}！ ボスまであと${remaining}マス。ぴったりではないので進まない！`;beep(145,.18);return}for(let step=0;step<result;step++){const node=map.nodes[state.routeNode];let next;if(node.next.length>1){next=state.routeNext||await askRouteV2(node);delete state.routeNext}else next=node.next[0];state.routeNode=next;state.boardPos=map.nodes[next].d;renderRouteV2(true);beep(420+step*25,.05);await wait(440)}renderRouteV2(false);save();const landed=map.nodes[state.routeNode];if(landed.type==='branch'){state.routeNext=await askRouteV2(landed);showRouteMapV2('進むルートを決めた！ 次のルーレットで出発！');return}await resolveRouteV2Square(landed.type)}
async function resolveRouteV2Square(type){if(type==='battle'){beginMobBattle();battle.boardBattle=true;battle.routeV2=true;battle.boardKind='battle';return}if(type==='mini'){beginRouteV2Mini();return}if(type==='boss'){askBossV2();return}const s=stats();if(type==='damage'){const damage=Math.max(3,Math.round(s.maxHp*(state.board?.24:.16)));state.hp=Math.max(1,state.hp-damage);showRouteMapV2(`💥 ダメージマス！ HPが ${damage}減った！`);beep(110,.18);return}if(type==='heal'){const hpBefore=state.hp,mpBefore=state.mp;state.hp=Math.min(s.maxHp,state.hp+Math.round(s.maxHp*.45));state.mp=Math.min(s.maxMp,state.mp+Math.round(s.maxMp*.35));showRouteMapV2(`💚 回復マス！ HP＋${state.hp-hpBefore}、MP＋${state.mp-mpBefore}！`);beep(720,.18);return}if(type==='xp'){const amount=xpForBoardLevels(state.board?7:2),levels=addExp(amount),nextStats=stats();if(levels){state.hp=nextStats.maxHp;state.mp=nextStats.maxMp;state.waters=3}showRouteMapV2(`⭐ 経験値 ${amount}！ レベルが ${levels}上がった！`);beep(900,.2);return}showRouteMapV2()}
function beginRouteV2Mini(){const index=state.board?5:0,m=miniBosses[index],lv=Math.min(MAX_LEVEL,state.level+2),maxHp=55+lv*8;battle={enemies:[{name:m.name,icon:m.icon,lv,maxHp,currentHp:maxHp,atk:6+lv*.95,spd:5+lv*1.25,xp:40+lv*10,id:0}],boss:false,miniBoss:true,boardBattle:true,routeV2:true,boardKind:'mini',lost:false,guard:false};startBattle(`小ボス・${m.name}が あらわれた！`)}
function startBossV2(){const map=routeMapsV2[state.board];beginBoss(map.boss);battle.boardBattle=true;battle.routeV2=true;battle.boardKind='boss'}
function routeV2Win(){playMusic('victory',true);battle.lost=false;const xp=battle.enemies.reduce((sum,e)=>sum+e.xp,0),levels=addExp(xp),newStats=stats();state.totalWins++;state.score+=xp*10+Math.max(0,state.hp)*3;if(levels){state.hp=newStats.maxHp;state.mp=newStats.maxMp;state.waters=3;state.carrots=Math.min(5,state.carrots+1)}else state.mp=Math.min(newStats.maxMp,state.mp+4);if(battle.boardKind==='boss'){if(battle.boss==='mayu'){state.board=1;state.routeNode=routeMapsV2[1].start;state.boardPos=0;state.stage=5;state.carrots=5;state.pendingMapMessage='まゆを倒した！ こうきへ続く新しいマップが現れた！'}else state.finished=true}else state.pendingMapMessage=battle.boardKind==='mini'?'小ボスを撃破！ このマスから再開！':'敵を倒した！ このマスから再開！';save();show('#resultScreen');$('#resultKicker').textContent=battle.boardKind==='boss'?'BOSS DEFEATED!':battle.boardKind==='mini'?'MINI BOSS DEFEATED!':'VICTORY!';$('#resultIcon').textContent=battle.boardKind==='boss'?'👑':battle.boardKind==='mini'?'🐾':'🏆';$('#resultTitle').textContent=battle.boss==='mayu'?'まゆに勝った！':battle.boss==='kouki'?'こうきを倒した！':`${battle.enemies.length}体を倒した！`;$('#resultText').innerHTML=`経験値 <b>${xp}</b> を てにいれた！<br>たるとは レベル${state.level}。${levels?'<br>お水の回数が3回に戻った！':''}`;$('#levelUp').classList.toggle('hidden',!levels);$('#levelUp').textContent=levels?`LEVEL UP!　${levels>1?'×'+levels:''}`:'LEVEL UP!';$('#resultBtn').textContent=state.finished?'エンディングへ':'すごろくへ戻る';beep(880,.18)}
const winBeforeRouteV2=win;
win=function(){if(battle&&battle.routeV2)return routeV2Win();return winBeforeRouteV2()};
function routeV2AfterResult(){if(!battle||!battle.routeV2)return pathAfterResult();if(battle.lost){state=fresh();showRouteMapV2('勇者たるとの冒険が、もう一度はじまる！');return}if(state.finished){ending();return}const message=state.pendingMapMessage;delete state.pendingMapMessage;showRouteMapV2(message)}
$('#advanceBtn').onclick=rollRouteV2;
$('#resultBtn').onclick=routeV2AfterResult;
const routeSpaceLabels={start:'スタート',battle:'敵',mini:'小ボス',damage:'ダメージ',heal:'回復',xp:'経験値',branch:'分岐',boss:'ボス'};
function renderRouteV3(){normalizeRouteV2();const map=routeMapsV2[state.board],wrap=$('#mapNodes'),scale=innerHeight<720?.75:1,current=map.nodes[state.routeNode];wrap.className='map-nodes route-board-v2';wrap.style.width=`${map.width}px`;wrap.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','route-svg');svg.setAttribute('viewBox',`0 0 ${map.width} ${520*scale}`);Object.values(map.nodes).forEach(node=>node.next.forEach(id=>{const next=map.nodes[id],line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',node.x);line.setAttribute('y1',node.y*scale);line.setAttribute('x2',next.x);line.setAttribute('y2',next.y*scale);svg.appendChild(line)}));wrap.appendChild(svg);Object.values(map.nodes).forEach(node=>{const info=squareInfo[node.type]||['🔀','分岐'],el=document.createElement('span');el.className=`map-node ${node.type}${node.id===state.routeNode?' current':''}${node.d<current.d?' visited':''}`;el.dataset.node=node.id;el.style.left=`${node.x}px`;el.style.top=`${node.y*scale}px`;el.innerHTML=`<b>${info[0]}</b><em>${routeSpaceLabels[node.type]}</em><small>${node.d}</small>`;el.setAttribute('aria-label',`${node.d}マス目 ${routeSpaceLabels[node.type]}`);wrap.appendChild(el)});const token=document.createElement('img');token.id='routeToken';token.className='route-token-v3';token.src='assets/taruto-card-v1.png';token.alt='たるとの現在地';token.style.left=`${current.x}px`;token.style.top=`${current.y*scale}px`;wrap.appendChild(token);setTimeout(()=>centerRouteNodeV3(state.routeNode,false),30)}
function centerRouteNodeV3(id,smooth=true){const map=routeMapsV2[state.board],node=map.nodes[id],viewport=$('#mapBackdrop');if(!node||!viewport)return;viewport.scrollTo({left:Math.max(0,node.x-viewport.clientWidth/2),behavior:smooth?'smooth':'auto'})}
async function moveTokenV3(id){const map=routeMapsV2[state.board],node=map.nodes[id],scale=innerHeight<720?.75:1,token=$('#routeToken');state.routeNode=id;state.boardPos=node.d;$$('.route-board-v2 .map-node').forEach(el=>el.classList.toggle('current',el.dataset.node===id));if(token){token.classList.add('walking');token.style.left=`${node.x}px`;token.style.top=`${node.y*scale}px`}centerRouteNodeV3(id,true);await wait(500);if(token)token.classList.remove('walking')}
function showRouteMapV3(custom){normalizeRouteV2();playMusic('map');show('#mapScreen');const map=routeMapsV2[state.board],node=map.nodes[state.routeNode],s=stats(),remaining=map.total-node.d;renderRouteV3();$('#mapBackdrop').classList.toggle('final-map',state.board===1);$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=map.chapter;$('#locationName').textContent=map.name;$('#mapMessage').textContent=custom||'丸いマスを線に沿って進もう！';$('#goalDistance').textContent=remaining?`ボスまで あと${remaining}マス`:'ボスマスに到着！';$('#advanceBtn').textContent=remaining?'ルーレットを回す！（1〜3）':'ボスへの挑戦を選ぶ';$('#advanceBtn').disabled=false;rouletteBusy=false;save()}
showRouteMapV2=showRouteMapV3;showMap=showRouteMapV3;
async function rollRouteV3(){if(rouletteBusy)return;normalizeRouteV2();const map=routeMapsV2[state.board],current=map.nodes[state.routeNode],remaining=map.total-current.d;if(!remaining){askBossV2();return}rouletteBusy=true;$('#advanceBtn').disabled=true;const display=$('#rouletteNumber');display.classList.add('spinning');let result=1;for(let i=0;i<12;i++){result=1+Math.floor(Math.random()*3);display.textContent=result;beep(330+i*25,.035);await wait(70+i*5)}display.classList.remove('spinning');if(result>remaining){rouletteBusy=false;$('#advanceBtn').disabled=false;$('#mapMessage').textContent=`${result}！ ボスまであと${remaining}マス。ぴったりではないので進まない！`;beep(145,.18);return}for(let step=0;step<result;step++){const node=map.nodes[state.routeNode];let next;if(node.next.length>1){next=state.routeNext||await askRouteV2(node);delete state.routeNext}else next=node.next[0];await moveTokenV3(next);beep(440+step*35,.06)}save();const landed=map.nodes[state.routeNode];if(landed.type==='branch'){state.routeNext=await askRouteV2(landed);showRouteMapV3('進むルートを決めた！ 次のルーレットで出発！');return}await resolveRouteV2Square(landed.type)}
$('#advanceBtn').onclick=rollRouteV3;
function renderSugorokuV4(){normalizeRouteV2();const map=routeMapsV2[state.board],wrap=$('#mapNodes'),scale=innerHeight<720?.75:1,current=map.nodes[state.routeNode];wrap.className='sugoroku-board';wrap.style.width=`${map.width}px`;wrap.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','sugoroku-lines');svg.setAttribute('viewBox',`0 0 ${map.width} ${520*scale}`);Object.values(map.nodes).forEach(node=>node.next.forEach(id=>{const next=map.nodes[id],line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',node.x);line.setAttribute('y1',node.y*scale);line.setAttribute('x2',next.x);line.setAttribute('y2',next.y*scale);svg.appendChild(line)}));wrap.appendChild(svg);Object.values(map.nodes).forEach(node=>{const info=squareInfo[node.type]||['🔀','分岐'],el=document.createElement('div');el.className=`sugoroku-node ${node.type}${node.id===state.routeNode?' current':''}`;el.dataset.node=node.id;el.style.left=`${node.x}px`;el.style.top=`${node.y*scale}px`;el.innerHTML=`<span class="node-icon">${info[0]}</span><strong class="node-label">${routeSpaceLabels[node.type]}</strong><small class="node-number">${node.d}</small>`;el.setAttribute('aria-label',`${node.d}マス目 ${routeSpaceLabels[node.type]}`);wrap.appendChild(el)});const token=document.createElement('img');token.id='sugorokuToken';token.className='sugoroku-token';token.src='assets/taruto-card-v1.png';token.alt='たるとの現在地';token.style.left=`${current.x}px`;token.style.top=`${current.y*scale}px`;wrap.appendChild(token);setTimeout(()=>centerSugorokuV4(state.routeNode,false),40)}
function centerSugorokuV4(id,smooth=true){const map=routeMapsV2[state.board],node=map.nodes[id],viewport=$('#mapBackdrop');if(node&&viewport)viewport.scrollTo({left:Math.max(0,node.x-viewport.clientWidth/2),behavior:smooth?'smooth':'auto'})}
async function moveSugorokuV4(id){const map=routeMapsV2[state.board],node=map.nodes[id],scale=innerHeight<720?.75:1,token=$('#sugorokuToken');state.routeNode=id;state.boardPos=node.d;$$('.sugoroku-node').forEach(el=>el.classList.toggle('current',el.dataset.node===id));if(token){token.classList.add('walking');token.style.left=`${node.x}px`;token.style.top=`${node.y*scale}px`}centerSugorokuV4(id,true);await wait(540);if(token)token.classList.remove('walking')}
function showSugorokuV4(custom){normalizeRouteV2();playMusic('map');show('#mapScreen');const map=routeMapsV2[state.board],node=map.nodes[state.routeNode],s=stats(),remaining=map.total-node.d;renderSugorokuV4();$('#mapBackdrop').classList.toggle('final-map',state.board===1);$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=map.chapter;$('#locationName').textContent=map.name;$('#mapMessage').textContent=custom||'丸の中のアイコンと種類を見て、線に沿って進もう！';$('#goalDistance').textContent=remaining?`ボスまで あと${remaining}マス`:'ボスマスに到着！';$('#advanceBtn').textContent=remaining?'ルーレットを回す！（1〜3）':'ボスへの挑戦を選ぶ';$('#advanceBtn').disabled=false;rouletteBusy=false;save()}
showRouteMapV2=showSugorokuV4;showMap=showSugorokuV4;
async function rollSugorokuV4(){if(rouletteBusy)return;normalizeRouteV2();const map=routeMapsV2[state.board],current=map.nodes[state.routeNode],remaining=map.total-current.d;if(!remaining){askBossV2();return}rouletteBusy=true;$('#advanceBtn').disabled=true;const display=$('#rouletteNumber');display.classList.add('spinning');let result=1;for(let i=0;i<12;i++){result=1+Math.floor(Math.random()*3);display.textContent=result;beep(330+i*25,.035);await wait(70+i*5)}display.classList.remove('spinning');if(result>remaining){rouletteBusy=false;$('#advanceBtn').disabled=false;$('#mapMessage').textContent=`${result}！ ボスまであと${remaining}マス。ぴったりではないので進まない！`;beep(145,.18);return}for(let step=0;step<result;step++){const node=map.nodes[state.routeNode];let next;if(node.next.length>1){next=state.routeNext||await askRouteV2(node);delete state.routeNext}else next=node.next[0];await moveSugorokuV4(next);beep(440+step*35,.06)}save();const landed=map.nodes[state.routeNode];if(landed.type==='branch'){state.routeNext=await askRouteV2(landed);showSugorokuV4('進むルートを決めた！ 次のルーレットで出発！');return}await resolveRouteV2Square(landed.type)}
$('#advanceBtn').onclick=rollSugorokuV4;
const fitBoardY=y=>60+y*.78;
function renderSugorokuFit(){normalizeRouteV2();const map=routeMapsV2[state.board],wrap=$('#mapNodes'),current=map.nodes[state.routeNode];wrap.className='sugoroku-board';wrap.style.width=`${map.width}px`;wrap.innerHTML='';const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','sugoroku-lines');svg.setAttribute('viewBox',`0 0 ${map.width} 520`);svg.setAttribute('preserveAspectRatio','none');Object.values(map.nodes).forEach(node=>node.next.forEach(id=>{const next=map.nodes[id],line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',node.x);line.setAttribute('y1',fitBoardY(node.y));line.setAttribute('x2',next.x);line.setAttribute('y2',fitBoardY(next.y));svg.appendChild(line)}));wrap.appendChild(svg);Object.values(map.nodes).forEach(node=>{const info=squareInfo[node.type]||['🔀','分岐'],el=document.createElement('div');el.className=`sugoroku-node ${node.type}${node.id===state.routeNode?' current':''}`;el.dataset.node=node.id;el.style.left=`${node.x}px`;el.style.top=`${fitBoardY(node.y)/520*100}%`;el.innerHTML=`<span class="node-icon">${info[0]}</span><strong class="node-label">${routeSpaceLabels[node.type]}</strong><small class="node-number">${node.d}</small>`;el.setAttribute('aria-label',`${node.d}マス目 ${routeSpaceLabels[node.type]}`);wrap.appendChild(el)});const token=document.createElement('img');token.id='sugorokuToken';token.className='sugoroku-token';token.src='assets/taruto-card-v1.png';token.alt='たるとの現在地';token.style.left=`${current.x}px`;token.style.top=`${fitBoardY(current.y)/520*100}%`;wrap.appendChild(token);setTimeout(()=>centerSugorokuV4(state.routeNode,false),40)}
async function moveSugorokuFit(id){const map=routeMapsV2[state.board],node=map.nodes[id],token=$('#sugorokuToken');state.routeNode=id;state.boardPos=node.d;$$('.sugoroku-node').forEach(el=>el.classList.toggle('current',el.dataset.node===id));if(token){token.classList.add('walking');token.style.left=`${node.x}px`;token.style.top=`${fitBoardY(node.y)/520*100}%`}centerSugorokuV4(id,true);await wait(540);if(token)token.classList.remove('walking')}
renderSugorokuV4=renderSugorokuFit;
moveSugorokuV4=moveSugorokuFit;
async function tapRoulette(){const trigger=$('#rouletteTrigger');if(rouletteBusy||trigger.disabled)return;trigger.disabled=true;try{await rollSugorokuV4()}finally{trigger.disabled=false}}
$('#rouletteTrigger').onclick=tapRoulette;
let rouletteCycleTimer=null,rouletteCycleValue=1;
function stopRouletteCycle(){if(rouletteCycleTimer){clearInterval(rouletteCycleTimer);rouletteCycleTimer=null}const trigger=$('#rouletteTrigger');if(trigger)trigger.classList.remove('cycling')}
function startRouletteCycle(){stopRouletteCycle();const trigger=$('#rouletteTrigger'),display=$('#rouletteNumber');if(!trigger||!display||$('#mapScreen').classList.contains('hidden'))return;trigger.disabled=false;trigger.classList.remove('confirmed');trigger.classList.add('cycling');display.textContent=rouletteCycleValue;rouletteCycleTimer=setInterval(()=>{rouletteCycleValue=rouletteCycleValue%3+1;display.textContent=rouletteCycleValue},95)}
const showSugorokuBeforeCycle=showSugorokuV4;
showSugorokuV4=function(custom){showSugorokuBeforeCycle(custom);setTimeout(startRouletteCycle,120)};
showRouteMapV2=showSugorokuV4;showMap=showSugorokuV4;
async function advanceFixedRoulette(result){normalizeRouteV2();const map=routeMapsV2[state.board],current=map.nodes[state.routeNode],remaining=map.total-current.d;if(!remaining){askBossV2();return}if(result>remaining){rouletteBusy=false;$('#mapMessage').textContent=`${result}！ ボスまであと${remaining}マス。ぴったりではないので進まない！`;beep(145,.18);setTimeout(startRouletteCycle,650);return}for(let step=0;step<result;step++){const node=map.nodes[state.routeNode];let next;if(node.next.length>1){next=state.routeNext||await askRouteV2(node);delete state.routeNext}else next=node.next[0];await moveSugorokuV4(next);beep(440+step*35,.06)}save();const landed=map.nodes[state.routeNode];if(landed.type==='branch'){state.routeNext=await askRouteV2(landed);showSugorokuV4('進むルートを決めた！ 次のルーレットで出発！');return}await resolveRouteV2Square(landed.type)}
async function stopAndAdvanceRoulette(){if(rouletteBusy||!rouletteCycleTimer)return;rouletteBusy=true;const trigger=$('#rouletteTrigger'),display=$('#rouletteNumber'),result=rouletteCycleValue;stopRouletteCycle();trigger.disabled=true;trigger.classList.add('confirmed');display.textContent=result;beep(920,.18);$('#mapMessage').textContent=`${result}で確定！ たるとが進むよ！`;await wait(850);trigger.classList.remove('confirmed');await advanceFixedRoulette(result);if(!$('#mapScreen').classList.contains('hidden')&&!rouletteCycleTimer&&!rouletteBusy)startRouletteCycle()}
$('#rouletteTrigger').onclick=stopAndAdvanceRoulette;
const enemyActionBeforeStun=enemyAction;
enemyAction=async function(enemy,s){if(enemy.stunTurns>0){enemy.stunTurns--;renderEnemies();updateBattle();log(`${enemy.name}は 目を回して動けない！\n残り ${enemy.stunTurns}回`);beep(210,.12);await wait(560);return}return enemyActionBeforeStun(enemy,s)};
const heroActionBeforeAdvanced=heroAction;
heroAction=async function(type,s){const buffWasActive=battle.heroAtkBuffTurns>0,boosted={...s,atk:s.atk*(buffWasActive?1.5:1)},target=activeEnemy(),advanced=['dig','snack','tackle','father','motherSupport','rampage','supreme'].includes(type);if(!advanced){await heroActionBeforeAdvanced(type,boosted);if(buffWasActive)battle.heroAtkBuffTurns--;return}let text='';state.mp-=skills[type].mp;if(type==='dig'){battle.evadeNext=true;text='たるとは 穴を掘ってかくれた！\n次の攻撃を1回だけ完全回避！';beep(280,.14)}if(type==='snack'){battle.heroAtkBuffTurns=3;text='たるとは おやつを食べた！\n攻撃力が1.5倍！ 3回継続！';beep(780,.16)}if(type==='tackle'){const dmg=Math.max(1,Math.round(boosted.atk*.5));target.currentHp-=dmg;showNumber(dmg,'damage',target);hitEnemies(false);text=`先制！ たるとタックル！\n${target.name}に ${dmg}ダメージ！`;beep(670,.13)}if(type==='father'){const hpBefore=state.hp,mpBefore=state.mp;state.hp=Math.min(s.maxHp,state.hp+Math.round(s.maxHp*.25));state.mp=Math.min(s.maxMp,state.mp+Math.round(s.maxMp*.2));showNumber(state.hp-hpBefore,'heal');text=`とーちゃんの応援！\nHP＋${state.hp-hpBefore}、MP＋${state.mp-mpBefore}！`;beep(820,.18)}if(type==='motherSupport'){const hpHeal=s.maxHp-state.hp,mpHeal=s.maxMp-state.mp;state.hp=s.maxHp;state.mp=s.maxMp;battle.heroAtkBuffTurns=2;showNumber(hpHeal,'heal');text=`かーちゃんの応援！\nHP・MP全回復！ 攻撃力1.5倍が2回！`;beep(940,.2)}if(type==='rampage'){let total=0;aliveEnemies().forEach(e=>{const dmg=Math.max(5,Math.round(boosted.atk*3*(.9+Math.random()*.2)));e.currentHp-=dmg;total+=dmg;showNumber(dmg,'critical',e)});hitEnemies(true);text=`たると大暴走！！\n敵全体に合計 ${total}ダメージ！`;beep(105,.24)}if(type==='supreme'){const dmg=100+Math.floor(Math.random()*201);target.currentHp-=dmg;battle.damageHalfTurns=3;showNumber(dmg,'critical',target);hitEnemies(false);text=`天上天下唯我独尊！！\n${target.name}に ${dmg}ダメージ！ 受けるダメージ半減が3回！`;beep(1020,.25)}if(buffWasActive&&!['snack','motherSupport'].includes(type))battle.heroAtkBuffTurns--;log(text);updateBattle();await wait(720)};
const enemyActionBeforeAdvanced=enemyAction;
enemyAction=async function(enemy,s){if(enemy.stunTurns>0)return enemyActionBeforeAdvanced(enemy,s);if(battle.evadeNext){battle.evadeNext=false;log(` ${enemy.name}の攻撃！\nたるとは穴にかくれて完全回避！`);beep(360,.14);await wait(560);return}const hpBefore=state.hp;await enemyActionBeforeAdvanced(enemy,s);if(battle.damageHalfTurns>0&&state.hp<hpBefore){const raw=hpBefore-state.hp,restored=Math.floor(raw/2);state.hp+=restored;battle.damageHalfTurns--;showNumber(restored,'heal');log(`天上天下唯我独尊の守り！\n受けたダメージを ${raw-restored} に半減！ 残り${battle.damageHalfTurns}回`);updateBattle();await wait(380)}};
function showLevelStatus(){if(!pendingLevelDetails)return;const d=pendingLevelDetails,round=n=>Math.round(n);$('#levelBefore').textContent=d.beforeLevel;$('#levelAfter').textContent=d.afterLevel;$('#hpBefore').textContent=round(d.before.maxHp);$('#hpAfter').textContent=round(d.after.maxHp);$('#mpBefore').textContent=round(d.before.maxMp);$('#mpAfter').textContent=round(d.after.maxMp);$('#atkBefore').textContent=round(d.before.atk);$('#atkAfter').textContent=round(d.after.atk);$('#defBefore').textContent=round(d.before.def);$('#defAfter').textContent=round(d.after.def);$('#spdBefore').textContent=round(d.before.spd);$('#spdAfter').textContent=round(d.after.spd);$('#levelStatus').classList.remove('hidden');beep(980,.2)}
$('#levelStatus').onclick=()=>{$('#levelStatus').classList.add('hidden');pendingLevelDetails=null};
let saveToastTimer=null;
function manualSave(){if(!state)return;save();const toast=$('#saveToast');clearTimeout(saveToastTimer);toast.classList.add('hidden');void toast.offsetWidth;toast.classList.remove('hidden');saveToastTimer=setTimeout(()=>toast.classList.add('hidden'),1850);beep(740,.12)}
function deleteSaveData(){if(!confirm('本当にセーブデータを消しますか？\n削除すると、レベルや現在位置は元に戻せません。\n\nキャンセルを押すと削除せずに戻ります。'))return;try{localStorage.removeItem(SAVE_KEY)}catch(_){}$('#continueBtn').classList.add('hidden');$('#deleteSaveBtn').classList.add('hidden');const toast=$('#saveToast');toast.textContent='セーブデータを消しました';toast.classList.remove('hidden');clearTimeout(saveToastTimer);saveToastTimer=setTimeout(()=>{toast.classList.add('hidden');toast.textContent='💾 セーブしました！'},1850)}
$('#saveGameBtn').onclick=manualSave;
$('#deleteSaveBtn').onclick=deleteSaveData;

// Version 4.2: scrolling hex-field sugoroku
const HEX_COLS=14,HEX_ROWS=5,HEX_COUNT=HEX_COLS*HEX_ROWS;
const hexLabels={normal:['・','通常'],xp:['⭐','経験値'],heal:['💚','回復'],spawn:['🐾','小ボス'],mountain:['⛰️','山'],start:['🏠','START'],boss:['👑','BOSS']};
function hexId(col,row){return col*HEX_ROWS+row}
function hexCell(id){return hexMaps[state.board].cells[id]}
function seededShuffle(list,seed){let n=seed>>>0;for(let i=list.length-1;i>0;i--){n=(n*1664525+1013904223)>>>0;const j=n%(i+1);[list[i],list[j]]=[list[j],list[i]]}return list}
function buildHexMap(board,seed=9271){const cells=[];for(let col=0;col<HEX_COLS;col++)for(let row=0;row<HEX_ROWS;row++){const id=hexId(col,row);cells.push({id,col,row,type:'normal',x:52+col*55,y:38+row*51+(col%2?25:0)})}const available=seededShuffle(cells.filter(c=>c.col>1&&c.col<HEX_COLS-2).map(c=>c.id),seed+board*331),take=(count,type,filter=()=>true)=>{let used=0;for(const id of available){if(used>=count)break;if(cells[id].type==='normal'&&filter(cells[id])){cells[id].type=type;used++}}};take(7,'xp');take(7,'heal');const mountainCols={};take(7,'mountain',cell=>(mountainCols[cell.col]||0)<2&&(mountainCols[cell.col]=(mountainCols[cell.col]||0)+1));take(4,'spawn');cells[0].type='start';cells[HEX_COUNT-1].type='boss';return{cells,width:52+(HEX_COLS-1)*55+52,name:board?'こうきの最終試験場':'まゆの草原ヘックス',chapter:board?'MAP 2・KOUKI HEX FIELD':'MAP 1・MAYU HEX FIELD',boss:board?'kouki':'mayu'}}
let hexMaps=[buildHexMap(0),buildHexMap(1)];
function hexNeighbors(id){const c=hexCell(id),dirs=c.col%2?[[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,1]]:[[1,0],[-1,0],[0,1],[0,-1],[1,-1],[-1,-1]];return dirs.map(([dc,dr])=>{const col=c.col+dc,row=c.row+dr;return col>=0&&col<HEX_COLS&&row>=0&&row<HEX_ROWS?hexId(col,row):-1}).filter(x=>x>=0)}
function hexRoute(){const route=[];for(let col=0;col<HEX_COLS;col++){const rows=[0,1,2,3,4];if(col%2)rows.reverse();rows.forEach(row=>route.push(hexId(col,row)))}return route}
const HEX_ROUTE=hexRoute();
function initialHexEnemies(board){const valid=HEX_ROUTE.filter(id=>id>8&&id<HEX_COUNT-6&&hexMaps[board].cells[id].type!=='mountain');const picks=seededShuffle(valid,(state.mapSeed||4441)+board*97).slice(0,8);return picks.map((cell,i)=>({id:`e${board}-${i}-${Date.now()}`,cell,icon:['🐺','🦅','🐍','🦊','👾'][i%5]}))}
function normalizeHexState(){state.board=Number.isFinite(state.board)?Math.min(1,state.board):0;state.stage=state.board?5:0;state.mapSeed=state.mapSeed||Math.floor(Math.random()*1e9);hexMaps=[buildHexMap(0,state.mapSeed),buildHexMap(1,state.mapSeed)];if(!state.hex||state.hex.board!==state.board){state.hex={board:state.board,player:0,turn:0,enemies:initialHexEnemies(state.board),defeated:0,consumed:[],movesLeft:0}}if(!Array.isArray(state.hex.enemies))state.hex.enemies=initialHexEnemies(state.board);if(!Array.isArray(state.hex.consumed))state.hex.consumed=[];state.hex.movesLeft=Number.isFinite(state.hex.movesLeft)?state.hex.movesLeft:0;state.hex.player=Math.max(0,Math.min(HEX_COUNT-1,state.hex.player||0));state.hex.turn=state.hex.turn||0}
function renderHexMap(){normalizeHexState();const map=hexMaps[state.board],wrap=$('#mapNodes'),current=hexCell(state.hex.player),reachable=new Set(state.hex.movesLeft>0?hexNeighbors(state.hex.player).filter(id=>hexCell(id).type!=='mountain'):[]);wrap.className='map-nodes hex-board';wrap.style.width=`${map.width}px`;wrap.innerHTML='';map.cells.forEach(cell=>{const type=state.hex.consumed.includes(cell.id)?'normal':cell.type,info=hexLabels[type],canMove=reachable.has(cell.id),el=document.createElement('div');el.className=`hex-space ${type}${cell.id===state.hex.player?' current':canMove?' reachable':' blocked'}`;el.dataset.cell=cell.id;el.style.left=`${cell.x}px`;el.style.top=`${cell.y}px`;el.innerHTML=`<span class="hex-icon">${info[0]}</span><strong>${info[1]}</strong><small>${cell.id+1}</small>${type==='spawn'?'<i class="hex-spawner">✦</i>':''}`;if(canMove){el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`${info[1]}マスへ移動`);el.onclick=()=>chooseHexMove(cell.id);el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseHexMove(cell.id)}}}wrap.appendChild(el)});state.hex.enemies.forEach(enemy=>{const cell=hexCell(enemy.cell),el=document.createElement('span');el.className='hex-enemy';el.dataset.enemy=enemy.id;el.style.left=`${cell.x}px`;el.style.top=`${cell.y}px`;el.textContent=enemy.icon;wrap.appendChild(el)});const token=document.createElement('img');token.id='hexToken';token.className='hex-token';token.src='assets/taruto-card-v1.png';token.alt='たると';token.style.left=`${current.x}px`;token.style.top=`${current.y}px`;wrap.appendChild(token);setTimeout(()=>centerHex(false),30)}
function centerHex(smooth=true){const cell=hexCell(state.hex.player),view=$('#mapBackdrop');view.scrollTo({left:Math.max(0,cell.x-view.clientWidth*.38),behavior:smooth?'smooth':'auto'})}
function showHexMap(custom){stopRouletteCycle();normalizeHexState();playMusic('map');show('#mapScreen');const screen=$('#mapScreen'),mustRoll=state.hex.movesLeft<=0;screen.classList.add('hex-mode');screen.classList.toggle('await-roll',mustRoll);renderHexMap();const map=hexMaps[state.board],s=stats(),boss=hexCell(state.hex.player).type==='boss';$('#mapBackdrop').classList.toggle('final-map',state.board===1);$('#mapLevel').textContent=`${state.level}/${MAX_LEVEL}`;$('#mapHp').textContent=`${state.hp}/${s.maxHp}`;$('#mapCarrots').textContent=state.carrots;$('#chapterLabel').textContent=map.chapter;$('#locationName').textContent=map.name;$('#mapMessage').textContent=custom||(mustRoll?'ルーレットをタップして、このターンの移動数を決めよう！':`あと${state.hex.movesLeft}マス。光る六角形をタッチ！`);$('#goalDistance').textContent=boss?'ボスマスに到着！':mustRoll?`ターン ${state.hex.turn+1}・敵 ${state.hex.enemies.length}体`:`残り ${state.hex.movesLeft}マス`;$('#rouletteNumber').textContent='?';rouletteBusy=false;hexMoveBusy=false;save();if(boss)setTimeout(askBossV2,250)}
showMap=showHexMap;
function hexNextOnRoute(){const index=HEX_ROUTE.indexOf(state.hex.player);return HEX_ROUTE[Math.min(HEX_ROUTE.length-1,index+1)]}
async function animateHexPlayer(next){state.hex.player=next;const cell=hexCell(next),token=$('#hexToken');if(token){token.classList.add('walking');token.style.left=`${cell.x}px`;token.style.top=`${cell.y}px`}$$('.hex-space').forEach((el,i)=>el.classList.toggle('current',i===next));centerHex(true);await wait(430);if(token)token.classList.remove('walking')}
function shortestEnemyStep(from,target){if(from===target)return from;const queue=[from],seen=new Set([from]),prev=new Map();while(queue.length){const at=queue.shift();for(const n of hexNeighbors(at)){if(seen.has(n)||hexCell(n).type==='mountain')continue;seen.add(n);prev.set(n,at);if(n===target){let step=n;while(prev.get(step)!==from)step=prev.get(step);return step}queue.push(n)}}return from}
async function moveHexEnemies(){for(const enemy of state.hex.enemies){enemy.cell=shortestEnemyStep(enemy.cell,state.hex.player);const cell=hexCell(enemy.cell),el=document.querySelector(`[data-enemy="${enemy.id}"]`);if(el){el.classList.add('moving');el.style.left=`${cell.x}px`;el.style.top=`${cell.y}px`}}await wait(430)}
function spawnHexEnemy(){const occupied=new Set(state.hex.enemies.map(e=>e.cell));const sources=hexMaps[state.board].cells.filter(c=>c.type!=='mountain'&&c.type!=='boss'&&!occupied.has(c.id)&&c.id!==state.hex.player);if(!sources.length)return false;const source=sources[Math.floor(Math.random()*sources.length)];state.hex.enemies.push({id:`spawn-${Date.now()}`,cell:source.id,icon:['🐺','🐍','🦅','👾'][Math.floor(Math.random()*4)]});return true}
function touchingHexEnemy(){return state.hex.enemies.find(e=>e.cell===state.hex.player)}
async function battleEntry(enemy){stopRouletteCycle();const overlay=document.createElement('div');overlay.className='battle-entry';overlay.innerHTML=`<span>ENCOUNTER!</span><b>${enemy.icon} 敵と接触！</b>`;document.body.appendChild(overlay);beep(120,.3);await wait(1000);overlay.remove();beginMobBattle();battle.boardBattle=true;battle.routeV2=true;battle.hexBattle=true;battle.hexEnemyId=enemy.id;battle.boardKind='battle'}
async function resolveHexLanding(){const enemy=touchingHexEnemy();if(enemy){await battleEntry(enemy);return}const cell=hexCell(state.hex.player),type=state.hex.consumed.includes(cell.id)?'normal':cell.type,s=stats();if(type==='boss'){askBossV2();return}if(type==='spawn'){state.hex.consumed.push(cell.id);beginAdaptiveMiniBoss();return}if(type==='heal'){const before=state.hp;state.hp=Math.min(s.maxHp,state.hp+Math.round(s.maxHp*.4));state.mp=Math.min(s.maxMp,state.mp+Math.round(s.maxMp*.25));state.hex.consumed.push(cell.id);showHexMap(`💚 回復マス！ HPが ${state.hp-before}回復。通常マスに変わった！`);return}if(type==='xp'){const amount=xpForBoardLevels(state.board?3:1),levels=addExp(amount),ns=stats();if(levels){state.hp=ns.maxHp;state.mp=ns.maxMp;state.waters=3}state.hex.consumed.push(cell.id);showHexMap(`⭐ 経験値 ${amount}を獲得！ 通常マスに変わった！`);return}showHexMap(state.hex.movesLeft>0?`あと${state.hex.movesLeft}マス移動できる！`:'敵も1マス動いた。次のターンへ！')}
async function advanceHex(result){normalizeHexState();if(hexCell(state.hex.player).type==='boss'){askBossV2();return}for(let i=0;i<result;i++){const next=hexNextOnRoute();if(next===state.hex.player)break;await animateHexPlayer(next);if(touchingHexEnemy()){await battleEntry(touchingHexEnemy());return}}state.hex.turn++;await moveHexEnemies();if(touchingHexEnemy()){await battleEntry(touchingHexEnemy());return}const spawned=Math.random()<.1&&spawnHexEnemy();if(spawned)$('#mapMessage').textContent='🌀 出現マスから新しい敵が湧き出した！';save();await resolveHexLanding()}
let hexMoveBusy=false;
async function chooseHexMove(destination){if(hexMoveBusy||state.hex.movesLeft<=0||!hexNeighbors(state.hex.player).includes(destination)||hexCell(destination).type==='mountain')return;hexMoveBusy=true;$$('.hex-space.reachable').forEach(el=>{el.classList.remove('reachable');el.classList.add('blocked')});const chosen=document.querySelector(`.hex-space[data-cell="${destination}"]`);if(chosen)chosen.classList.add('moving-to');await animateHexPlayer(destination);state.hex.movesLeft--;if(touchingHexEnemy()){await battleEntry(touchingHexEnemy());return}let spawned=false;if(state.hex.movesLeft<=0){state.hex.turn++;await moveHexEnemies();if(touchingHexEnemy()){await battleEntry(touchingHexEnemy());return}spawned=Math.random()<.18&&spawnHexEnemy()}save();await resolveHexLanding();if(spawned&&$('#mapScreen:not(.hidden)'))$('#mapMessage').textContent='敵が新しく出現した！'}
stopAndAdvanceRoulette=async function(){if(rouletteBusy||!rouletteCycleTimer)return;rouletteBusy=true;const trigger=$('#rouletteTrigger'),display=$('#rouletteNumber'),result=rouletteCycleValue;stopRouletteCycle();trigger.disabled=true;trigger.classList.add('confirmed');display.textContent=result;beep(920,.18);$('#mapMessage').textContent=`${result}で確定！`;await wait(700);trigger.classList.remove('confirmed');await advanceHex(result)};
$('#rouletteTrigger').onclick=()=>stopAndAdvanceRoulette();
const askBossBeforeHex=askBossV2;
askBossV2=function(){normalizeHexState();if(hexCell(state.hex.player).type!=='boss')return;askBossBeforeHex();const fight=$('#fightBossBtn');fight.onclick=()=>{$('#mapChoice').classList.add('hidden');startBossV2();battle.hexBattle=true};$('#returnStartBtn').onclick=()=>{$('#mapChoice').classList.add('hidden');state.hex.player=0;showHexMap('スタート地点へ戻った。レベルを上げて再挑戦しよう！')}};
const resultBeforeHex=$('#resultBtn').onclick;
$('#resultBtn').onclick=function(){if(!battle||!battle.hexBattle)return resultBeforeHex();if(battle.lost){state=fresh();showHexMap('倒れてしまった。レベル1から再スタート！');return}if(state.finished){ending();return}if(battle.hexEnemyId&&state.hex)state.hex.enemies=state.hex.enemies.filter(e=>e.id!==battle.hexEnemyId);if(battle.boardKind==='boss'&&battle.boss==='mayu'){state.mayuJoined=true;state.hex={board:1,player:0,turn:0,enemies:initialHexEnemies(1),defeated:0,consumed:[],movesLeft:0};state.pendingMapMessage='まゆが改心して仲間になった！ 次の戦いから一緒に参加する！'}showHexMap(state.pendingMapMessage||'敵を倒した！ 冒険を続けよう！');delete state.pendingMapMessage};

// Version 4.3: balance, companions, one-shot spaces and debug battles
const skillUnlockTable=[['しっぽを振り回す',3],['穴を掘る',5],['おやつパワー',8],['たるとタックル',12],['とーちゃん応援',18],['友情の呼び声',20],['かーちゃん応援',25],['たると大暴走',35],['天上天下唯我独尊',50]];
const addExpBeforeV43=addExp;
addExp=function(amount){const before=state.level,levels=addExpBeforeV43(amount);if(levels&&pendingLevelDetails)pendingLevelDetails.unlocked=skillUnlockTable.filter(([,lv])=>lv>before&&lv<=state.level).map(([name])=>name);return levels};
const showLevelBeforeV43=showLevelStatus;
showLevelStatus=function(){showLevelBeforeV43();const unlocked=pendingLevelDetails&&pendingLevelDetails.unlocked||[],notice=$('#newSkillNotice');notice.classList.toggle('hidden',!unlocked.length);notice.innerHTML=unlocked.length?unlocked.map(name=>`「${name}」を覚えた！`).join('<br>'):''};
const updateSkillsBeforeV43=updateSkillUnlocks;
updateSkillUnlocks=function(){updateSkillsBeforeV43();$('#reviveSkillBtn').classList.toggle('hidden',state.level<20)};
const updateBattleBeforeV43=updateBattle;
updateBattle=function(){updateBattleBeforeV43();const buffs=[];if(battle.heroAtkBuffTurns>0)buffs.push(`⚔ 攻撃力 1.5倍・残り${battle.heroAtkBuffTurns}回`);if(battle.damageHalfTurns>0)buffs.push(`🛡 被ダメージ半減・残り${battle.damageHalfTurns}回`);$('#battleBuffs').classList.toggle('hidden',!buffs.length);$('#battleBuffs').textContent=buffs.join('　');if(battle.mayu){$('#mayuAllyHp').textContent=`HP ${Math.max(0,battle.mayu.hp)}/${battle.mayu.maxHp}`;$('#mayuAlly').classList.remove('hidden')}else $('#mayuAlly').classList.add('hidden')};
const startBattleBeforeV43=startBattle;
startBattle=function(text){if(state.mayuJoined&&battle.boss!=='mayu')battle.mayu={level:25,maxHp:150,hp:150,mp:60,atk:42,spd:44};startBattleBeforeV43(text);$('#enemySprite').classList.toggle('kouki-party',battle.boss==='kouki')};
async function mayuAutoAction(){const m=battle.mayu;if(!m||m.hp<=0||!aliveEnemies().length)return;const target=activeEnemy();if(state.hp<stats().maxHp*.38&&m.mp>=8){const heal=Math.round(stats().maxHp*.3);state.hp=Math.min(stats().maxHp,state.hp+heal);m.mp-=8;showNumber(heal,'heal');log(`まゆの「カフェラテ差し入れ」！\nたるとのHPが ${heal}回復！`)}else if(Math.random()<.25&&m.mp>=7){aliveEnemies().forEach(e=>e.attackDownTurns=Math.max(e.attackDownTurns||0,2));m.mp-=7;log('まゆの「女子大生トーク」！\n敵全体の攻撃力が低下！')}else{const dmg=Math.max(5,Math.round(m.atk*(.75+Math.random()*.25)));target.currentHp-=dmg;showNumber(dmg,'damage',target);hitEnemies(false);log(`まゆの「レポートラッシュ」！\n${target.name}に ${dmg}ダメージ！`)}updateBattle();await wait(520)}
const heroActionBeforeV43=heroAction;
heroAction=async function(type,s){if(type==='bite'){const target=activeEnemy();state.mp-=skills.bite.mp;const dmg=Math.max(3,Math.round(s.atk*(.85+Math.random()*.2)));target.currentHp-=dmg;target.bleedTurns=2;target.bleedPower=Math.max(1,Math.round(s.atk*.15));showNumber(dmg,'damage',target);hitEnemies(false);log(`たるとの かみつき！\n${target.name}に ${dmg}ダメージ＋弱い出血！`);updateBattle();await wait(560)}else if(type==='revive'){if(state.mp<15){log('友情の呼び声を使うMPが足りない！');await wait(350)}else if(!battle.mayu||battle.mayu.hp>0){log('いまは生き返らせる仲間がいない！');await wait(350)}else{state.mp-=15;battle.mayu.hp=Math.round(battle.mayu.maxHp*.5);log('たるとの「友情の呼び声」！\nまゆがHP半分で復活！');updateBattle();await wait(600)}}else await heroActionBeforeV43(type,s);if(battle.mayu&&battle.mayu.hp>0&&aliveEnemies().length)await mayuAutoAction()};
async function heroRevivalBanner(title,text){const banner=document.createElement('div');banner.className='revival-banner';banner.innerHTML=`<small>ONE MORE CHANCE</small><strong>${title}</strong><span>${text}</span>`;$('#battleScreen').appendChild(banner);beep(780,.35);await wait(1000);banner.remove()}
const enemyActionBeforeV43=enemyAction;
enemyAction=async function(enemy,s){if(battle.mayu&&battle.mayu.hp>0&&Math.random()<.28&&!enemy.bigMove){const dmg=Math.max(1,Math.round(enemy.atk-s.def*.45));battle.mayu.hp-=dmg;log(`${enemy.name}の攻撃！\nまゆは ${dmg}ダメージ！`);updateBattle();await wait(480);return}await enemyActionBeforeV43(enemy,s);if(state.hp<=0&&['mayu','kouki'].includes(battle.boss)&&!battle.heroRevived){battle.heroRevived=true;state.hp=s.maxHp;battle.enemies.forEach(e=>e.currentHp=e.maxHp);const boss=battle.enemies.find(e=>e.id===0)||battle.enemies[0];renderEnemies();await heroRevivalBanner('たると復活！',battle.boss==='kouki'?'こうきと後輩2人もHP満タン！ ここから再戦！':`${boss.name}もHP満タン！ ここから再戦！`);updateBattle()}else if(state.hp<=0&&battle.mayu&&battle.mayu.hp>0&&battle.mayu.level>=20&&!battle.mayuReviveUsed){battle.mayuReviveUsed=true;state.hp=Math.round(s.maxHp*.5);await heroRevivalBanner('まゆの友情コール！','たるとがHP半分で復活！');updateBattle()}};
const beginBossBeforeV43=beginBoss;
beginBoss=function(type){if(type!=='kouki')return beginBossBeforeV43(type);const lv=Math.max(10,state.level),mainHp=5000;battle={enemies:[{name:'こうき',image:'assets/kouki-upper-body-v1.png',lv,maxHp:mainHp,currentHp:mainHp,atk:22+lv,spd:24+lv,xp:2500,id:0,bigMove:'受験プレッシャー砲'},{name:'ワル後輩・レン',icon:'😈',lv:Math.max(1,lv-4),maxHp:100+lv*4,currentHp:100+lv*4,atk:12+lv*.65,spd:18+lv*.65,xp:500,id:1},{name:'ワル後輩・ショウ',icon:'🥷',lv:Math.max(1,lv-3),maxHp:110+lv*4,currentHp:110+lv*4,atk:13+lv*.65,spd:16+lv*.7,xp:550,id:2}],boss:'kouki',lost:false,guard:false};startBattle('こうきと悪そうな後輩2人が あらわれた！')};
function beginAdaptiveMiniBoss(){const lv=state.level,m=miniBosses[state.board?5:0],hp=50+lv*8;battle={enemies:[{name:m.name,icon:m.icon,lv,maxHp:hp,currentHp:hp,atk:5+lv*.9,spd:5+lv*1.05,xp:30+lv*8,id:0}],boss:false,miniBoss:true,boardBattle:true,routeV2:true,hexBattle:true,boardKind:'mini',lost:false,guard:false};startBattle(`出現マスから小ボス・${m.name}が現れた！`)}
async function rollHexTurn(){if(rouletteBusy||state.hex.movesLeft>0)return;rouletteBusy=true;const trigger=$('#rouletteTrigger'),display=$('#rouletteNumber');trigger.disabled=true;display.classList.add('spinning');let result=1;for(let i=0;i<18;i++){result=1+Math.floor(Math.random()*6);display.textContent=result;beep(350+i*18,.03);await wait(55)}display.classList.remove('spinning');trigger.classList.add('confirmed');state.hex.movesLeft=result;save();await wait(650);trigger.classList.remove('confirmed');trigger.disabled=false;showHexMap(`🎲 ${result}！ 光っているマスを選んで、あと${result}マス進もう！`)}
$('#rouletteTrigger').onclick=rollHexTurn;
const loseBeforeV43=lose;
lose=function(){battle.restartLevel=Math.max(1,Math.floor(state.level/2));battle.lost=true;show('#resultScreen');$('#resultKicker').textContent='GAME OVER';$('#resultIcon').textContent='💫';$('#resultTitle').textContent='たるとは力つきた…';$('#resultText').innerHTML=`レベル${battle.restartLevel}から再スタートできます。`;$('#levelUp').classList.add('hidden');$('#resultBtn').textContent=`レベル${battle.restartLevel}から再開`};
const resultHandlerBeforeV43=$('#resultBtn').onclick;
$('#resultBtn').onclick=function(){if(battle&&battle.lost){const lv=battle.restartLevel||1;state=fresh();state.level=lv;const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;save();showHexMap(`レベル${lv}から再スタート！`);return}return resultHandlerBeforeV43()};
function setDebugLevel(){const lv=Math.max(1,Math.min(50,Number($('#debugLevel').value)||1));state=fresh();state.level=lv;const s=stats();state.hp=s.maxHp;state.mp=s.maxMp;return lv}
$('#debugBtn').onclick=()=>$('#debugModal').classList.remove('hidden');$('#debugClose').onclick=()=>$('#debugModal').classList.add('hidden');
$('#debugMayu').onclick=()=>{setDebugLevel();$('#debugModal').classList.add('hidden');beginBoss('mayu');battle.debugBattle=true};
$('#debugKouki').onclick=()=>{setDebugLevel();state.board=1;state.mayuJoined=true;$('#debugModal').classList.add('hidden');beginBoss('kouki');battle.debugBattle=true};
init();
